### ISSUE TITLE
UnicodeEncodeError on 1.3.0

### ISSUE THREAD

**Issue by mattclay** [adrienverge/yamllint#10]
The new yamllint 1.3.0 release raises an exception when scanning a file with a unicode comment:

```
UnicodeEncodeError: 'ascii' codec can't encode character u'\u20ac' in position 2: ordinal not in range(128)
```

The file tested contained:

```
# €
```

**Comment by adrienverge** [comment]
Hi @mattclay, thanks for reporting this!

This is a problem with Python 2 only, when parsing directive comments (`# yamllint disable rule...`)

I just pushed a fix and associated tests. And will release a new version in the next minutes.

Thanks again
