### ISSUE TITLE
YAML files with Mac and Windows line break sequences not supported

### ISSUE THREAD

**Issue by sbaudoin** [adrienverge/yamllint#102]
Although YAML 1.1 says that the Mac, Windows and Unicode line breaks are valid end of line markers, yamllint does not support that. Example with a simple version 1.11.0 of yamllint:

**test.yml**

    ---
    key: value

If you encode this file with Unix-style line breaks, yamllint just ends nicely:

    bash-4.2$ yamllint test.yml
    bash-4.2$ echo $?
    0

If you encode this file with Windows-style line breaks, yamllint complains:

    bash-4.2$ yamllint test.yml
    test2.yml
      1:4       error    wrong new line character: expected \n  (new-lines)

It is even worth with Mac-style line breaks:

    bash-4.2$ yamllint test.yml
    test2.yml
      1:16      error    no new line character at the end of file  (new-line-at-end-of-file)

So please, can you support all "official" YAML line breaks, please?

**Comment by adrienverge** [comment]
Have you looked at the documentation? Especially the [`new_line_at_end_of_file` rule](
https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.new_line_at_end_of_file).

Like other yamllint rules, it does not enforce a YAML standard, but a user-defined one (like avoiding the mixed usage of `\n` and `\r\n` for example).

**Comment by sylv704** [comment]
Indeed I didn't pay attention to the new-lines rule (the one that really apply). However, some rules do not work with DOS-line line breaks even if new-lines is set to dos. This is at least the case with the empty-lines rule. So there is an issue there at least with empty-lines.

And we should be also able to set new-lines to mac because it is supposed to be supported by the YAML standard.

**Comment by adrienverge** [comment]
Hi @sbaudoin, could you test with #174? It aims to fix the problem.

**Comment by adrienverge** [comment]
No feedback from issue author, but should be fixed by https://github.com/adrienverge/yamllint/pull/174.
