### ISSUE TITLE
npm install yamllint

### ISSUE THREAD

**Issue by ehmicky** [adrienverge/yamllint#103]
It would be great for Node users to be able to install this package without requiring `pip`.

Also reaching out to this big pool of developers might help this project get stars and contributors. At the moment, there is no real YAML linting package on npm and the name `yamllint` [is not registered yet](https://www.npmjs.com/package/yamllint).

I am not sure what is the best approach though. I can help with the creation of the `package.json` and publishing to npm. However this is not enough as `pip` dependencies would not be installed after `npm install yamllint`. Maybe `pip install --user` can be run before pushing to npm? I am not sure what's best here.

PS: thanks for this project, this is super useful!

**Comment by adrienverge** [comment]
Hi @ehmicky, thanks for this advice, I admit this is a good idea.
Are there any good practices for installing a Python program with npm? The simplest would be to call `pip install --user` from `package.json`'s install script, but it would obviously fail on systems that don't have `pip` installed.

**Comment by ehmicky** [comment]
Maybe the install script can first install `pip` itself locally, but I am not sure if this is the best way to solve this. I have some good insights into Node.js and `npm` but not into `pip` unfortunately.

Also Python will need to be installed as well, correct? Makes me wonder if this is not a bad idea to mix Node.js and Python ecosystems.

**Comment by roryabraham** [comment]
Would love to see this feature. I recently built a lot of CI/CD using GitHub Actions, and that framework relies heavily on YAML files. Would like to standardize YAML style, and this seems like by far the most stable / well developed framework for yaml linting.

**Comment by adrienverge** [comment]
I'm closing this, because in general we cannot expect non-JavaScript programs to be installable from npm.
