### ISSUE TITLE
[Feature request] Add more options for indentation.

### ISSUE THREAD

**Issue by zapashcanon** [adrienverge/yamllint#11]
Hi,

I started using yamllint recently for a project. I would like my yaml files fo follow the Symfony coding conventions. Unfortunately, it's not possible to do, as some indentations options are not available. Especially being able to allow/require this kind of indentation:

```
k_phoen_contact:
    redirect_url:   contact
    sender:         { address: 'no-reply@bar.baz' }
    receiver:       { address: foo@bar.baz }
```

So, I'd like to ask you if you could add this feature. :)

**Comment by adrienverge** [comment]
Hi @zapashcanon, I'm glad to hear you use/like yamllint!

Unfortunately I don't have much time for this these days. Contributions are welcome.

In the meantime you could use this conf to *allow* your style (but not to *require* it, sorry):

```yaml
rules:
  colons:
    max-spaces-after: -1
```

**Comment by zapashcanon** [comment]
Yep, thx. I though about max-spaces-after: 4, but I'd like to require it rather.

As I don't know Python so much and don't have a lot of time neither, Idk if I'll be able to come up with something. Anyway, I'll try to take a look at your code when I'll be able to.
