### ISSUE TITLE
"$ yamllint ." inside root doesn't operate recursively

### ISSUE THREAD

**Issue by JohnVonNeumann** [adrienverge/yamllint#111]
Hey there, so I've scratched my head with this one a bit, I'm really confused. So I have a directory structure like this:

```
appname Pipfile  Pipfile.lock  README.md  sceptre
```

Yet when I run this, even though my `sceptre dir` contains another `dir` named `templates`, which contains a lot of yaml files that have errors. I get no response, it runs that is, to completion, with no errors.

Yet when I jump back one level and run `yamllint directoryname`, it goes into the sceptre dir and all that, finds the yaml files and outputs errors. It's really quite strange. 

yamllint version: yamllint==1.11.1

Installed using `pipenv install yamllint`

Ubuntu16.04

**Comment by adrienverge** [comment]
Hi @JohnVonNeumann, it's strange indeed. Could you upload a tar archive of `directoryname`?
