### ISSUE TITLE
comments rule with require-starting-space: true should special case shebang

### ISSUE THREAD

**Issue by adamchainz** [adrienverge/yamllint#116]
Some yaml files might start with a shebang on their first line, e.g. ansible playbooks with `#!/usr/bin/env ansible-playbook`. The `require-starting-space` option currently complains about such lines, asking you to break them by inserting a space between `#` and `!`, it could special case them.

**Comment by adrienverge** [comment]
I acknowledge this behaviour, but the rule is explicit: it forbids spaces after `#`, and shebangs have a `!`.

In my opinion the best approach would be to add an option to the rule, what do you think?

**Comment by adamchainz** [comment]
Sure we can add an option. Default on or off? I'd lean towards on as it's such a narrow case...

**Comment by adrienverge** [comment]
Yes I guess it could be on by default... Do you have an idea for the option name? `ignore-shebang`? `ignore-shebangs`?

**Comment by adamchainz** [comment]
`ignore-shebang` sounds fine to me

**Comment by mattiasb** [comment]
See #151 :)
