### ISSUE TITLE
`find_files_recursively` is not recursive at all

### ISSUE THREAD

**Issue by lwille** [adrienverge/yamllint#122]
From all I understand about programming, the `find_files_recursively` is not recursive: It's not calling itself. It only goes through a list of paths and, if there is a directory, uses `os.walk` to read it. It does not call itself with the list of directories returned by `os.walk`.

https://github.com/adrienverge/yamllint/blob/e4e99f0aba5bc894712a720d8516db556e48acf1/yamllint/cli.py#L30-L38

This might also be a reason for #111.

**Comment by adrienverge** [comment]
Why is it a problem?

**Comment by lwille** [comment]
Assuming I have a deep directory structure with YAML files, in this current implementation `yamllint .` will only consider files in the current directory and first subdirectory level.

**Comment by adrienverge** [comment]
> `yamllint .` will only consider files in the current directory and first subdirectory level.

No.

Have you checked out the test for that function, and the `s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/file.yaml` example?

https://github.com/adrienverge/yamllint/blob/e4e99f0aba5bc894712a720d8516db556e48acf1/tests/test_cli.py#L80-L111

**Comment by lwille** [comment]
Hmm, that looks fine indeed.
And I’m sorry, didn’t properly read about os.walk - but then I don’t understand why it doesn’t work for me. 

However I’m now resorting to git ls-files which is much faster.
