### ISSUE TITLE
Integrate with .gitignore's

### ISSUE THREAD

**Issue by mcandre** [adrienverge/yamllint#125]
Automatically exclude file paths ignored in version control, eg .gitignore

**Comment by memotype** [comment]
@mcandre  `git ls-files` will give you a list of non-ignored files.

**Comment by mcandre** [comment]
@memotype Yes, but performing the integration between yamllint and git CLI requires either a non-portable, flakey shell script, or a dedicated, third party application to perform the right command calls and piping. This could be done directly by yamllint itself.

**Comment by adrienverge** [comment]
This could, but I think it's out of scope. Moreover if `.gitignore` is handled, then `~/.gitignore` should be too, then `.hgignore`, etc.

**Comment by memotype** [comment]
> @memotype Yes, but performing the integration between yamllint and git CLI requires either a non-portable, flakey shell script, or a dedicated, third party application to perform the right command calls and piping. This could be done directly by yamllint itself.

I don't even remember how I found this issue or felt the need to comment (lol), but I think what I was trying to say is that you could easily do something like

```
git ls-files | grep -E '.*\.ya?ml$' | xargs yamllint [options]
```

Nothing too flaky or non-portable about that (unless your old-ass AIX system doesn't have xargs or something). Stick that in an alias in your .bash_profile (or whatever shell startup script). Trust me, that will be perfectly portable to any system with a posix shell. If you need a version for Windows, I'm sure something similar can be done.

**Comment by adrienverge** [comment]
I agree with @memotype. You can also use:

```shell
yamllint $(git ls-files '*.yaml' '*.yml')
```

as show in example in:
https://github.com/adrienverge/yamllint/blob/881d30188343287ad2684ce45dadad4e7738aa61/.travis.yml#L18
