### ISSUE TITLE
Support for yaml files with multiple "documents"

### ISSUE THREAD

**Issue by dims** [adrienverge/yamllint#132]
Kubernetes uses yaml files with multiple documents using the `---` as a separator. Looks like this is supported by the spec too [1]. Please see examples in [2].

Any chance we can enhance yamllint to work with such files?

[1] http://yaml.org/spec/1.2/spec.html#id2800132
[2] https://cs.k8s.io/?q=%5E---&i=nope&files=.*%5C.yaml&repos=kubernetes/kubernetes

**Comment by adrienverge** [comment]
Have you read the docs or done a quick search before posting this? Why do you say yamllint doesn't work with such files? Do you have an example?
https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.document_start

**Comment by bdelsaz** [comment]
Just a note for anyone looking for this issue; please be aware that yamllint behaves differently on windows and linux. 
If I do: 
`find -name "*.yaml" | xargs yamllint`

In Windows it will complain about the 'multi-document' @dims was talking about, in linux it will work just fine. I searched the docs to find the explanation but did not find anything, probably differences in the python implementation (?)
