### ISSUE TITLE
Can't disable coloured output

### ISSUE THREAD

**Issue by alexjurkiewicz** [adrienverge/yamllint#14]
When using yamllint with default output format in eg a build script, the default colour output results in ugly data in the plain text log:

```
[4m./global.yaml[0m
  [2m1439:52[0m   [31merror[0m    no new line character at the end of file  [2m(new-line-at-end-of-file)[0m
```

You can work around this by setting `-f parsable` but the format is less human readable. It would be nice to have a way to output standard format without colour. I'm not sure if that would best be a third `-f` option, or a new `--colour never` option (like grep) or a new `--no-colour` option.

**Comment by adrienverge** [comment]
Hey @alexjurkiewicz,

I'm thinking about another solution: to have yamllint detect if output is a terminal or if it is a file / a pipe. Then, colours would only be printed for terminals. What do you think?

**Comment by alexjurkiewicz** [comment]
That's good, but I would prefer default behaviour like grep: default is
Auto detection, but you can force colours on or off. Some logging systems
support ANSI colors.

**Comment by adrienverge** [comment]
I understand. I'll merge the auto-detection feature I just implemented since I think it will serve 80% use-cases, and anyone is free to implement a `--format standard-color` option.
