### ISSUE TITLE
Respect PY_COLORS variable

### ISSUE THREAD

**Issue by ssbarnea** [adrienverge/yamllint#143]
Multiple python tools do rely on PY_COLORS variable to decide if they should enable coloring or not.

When not defined tools would assume its current behaviour (likely auto-detection of interactive tty).
When set to "1" it would act as force colors (ignores detections)
When set to "0" it would force not to use colors.

Also, please make a new release as is impossible to make the last release colored on CI due to the wrong conditions: cannot bypass tty detection, and CI does not have an interactive tty.

**Comment by adrienverge** [comment]
- `PY_COLORS` does not seem to be very standard: when searching for it on Google, I see only one relevant result on the first page.
- I've just released version 1.13.0: you can force a colored output using `yamllint -f colored`.
