### ISSUE TITLE
Deploy yamllint to Alpine apk repository

### ISSUE THREAD

**Issue by flaksp** [adrienverge/yamllint#154]
Because most of the time we run yamllint inside CI, it will be very useful to create official [apk package](https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management) and implement automatic releases deployment to it.

Related articles that may help:
* [Creating an Alpine package](https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package)

**Comment by brunowego** [comment]
@neluzhin you right. I'm looking for exactly it now.

**Comment by brunowego** [comment]
Advanced Packaging Tool (APT) have installation package:

```sh
sudo apt update
sudo apt -y install yamllint
```

**Comment by brunowego** [comment]
@neluzhin by now, I'm using something like this:

## Build

```sh
cat << EOF | docker build $(echo $DOCKER_BUILD_OPTS) -t example/yamllint -
FROM alpine:3.9

RUN apk add --no-cache py3-setuptools==40.6.3-r0

RUN pip3 install --no-cache-dir yamllint===1.16.0

ENTRYPOINT ["/usr/bin/yamllint"]

EOF
```

## Running

```sh
docker run -it --rm \
  $(echo $DOCKER_RUN_OPTS) \
  -h yamllint \
  --name yamllint \
  example/yamllint:latest -h
```

> Ignore `$DOCKER_BUILD_OPTS`, `$DOCKER_RUN_OPTS`, I'm behind a proxy.

**Comment by brunowego** [comment]
Out of scope of this issue. @adrienverge you are accepting a pull request for docker support?

**Comment by adrienverge** [comment]
@brunowego no, I still don't accept them, see https://github.com/adrienverge/yamllint/pull/179#issuecomment-495080410.
