### ISSUE TITLE
Feature request: read from standard input

### ISSUE THREAD

**Issue by miguelbarao** [adrienverge/yamllint#159]
Hello.
I'm checking yaml files generated on the fly by other programs that print yaml to the standard output.

It would be awesome if I could pipe the other programs to yamllint, something like

```bash
prints_yaml_to_stdout | yamllint --
```

Currently I have to save the outputs to a file to be able to check them.
Thanks!

**Comment by adrienverge** [comment]
Hello, this issue already exists: closing in favor of #47.
