### ISSUE TITLE
Support YAML front-matter in markdown files

### ISSUE THREAD

**Issue by Mr0grog** [adrienverge/yamllint#161]
A lot of static site generators use Markdown files, but add a YAML block at the top with metadata. Do you have any interest in having built-in support for linting those metadata blocks when `*.md` files are encountered? (I know I can do this manually by parsing the file myself and calling `yamllint.linter.run()`, but it’d be nice if the CLI supported it.)

I’d be happy to work on a PR adding this to the `cli` module.

**Comment by adrienverge** [comment]
Hey @Mr0grog, I understand your use-case, but I'm sorry, we won't start supporting custom formats directly from the CLI.

**Comment by Mr0grog** [comment]
OK, thanks for the quick reply.

**Comment by adrienverge** [comment]
It's still not planned to support custom formats, but for front matter you can workaround this easily:

```yaml
---
a: this is a
b: front matter file
a: duplicated key
---
<h1>This is not YAML</h1>
```
```bash
cat file.whatever \
  | python -c 'import sys; print(sys.stdin.read().split("\n---\n")[0])' \
  | yamllint -
```
