### ISSUE TITLE
Feature request: Add only configuration option

### ISSUE THREAD

**Issue by legendetm** [adrienverge/yamllint#162]
Please add option **only** similarly to **ignore** so we can list files or directories where the rule should be forced.

We are forcing key-ordering to only subset of YAML files, for this we have to *ignore* all other files/directories, to force key-ordering, for these YAML files.

**Comment by adrienverge** [comment]
Hi @legendetm, sorry for the late answer. What about simply using:

    yamllint dir/that/should/be/enforced other/dir other/file.yaml

Other idea: use the `!` from gitignore path patterns, to include **only** some directories?

**Comment by legendetm** [comment]
Thanks @adrienverge, the `!` trick works. 

We are running the `yamllint` through `overcommit` which executes `yamllint` for all changed yml files before git commit.
