### ISSUE TITLE
Python 3.7 deprecation warning causes failure in test_run_auto_output_without_tty_output

### ISSUE THREAD

**Issue by jayvdb** [adrienverge/yamllint#165]
This is a flaky error, occurring occasionally when I do builds on openSUSE build service, Tumbleweed rolling release.

```
[  139s] ======================================================================
[  139s] FAIL: test_run_auto_output_without_tty_output (tests.test_cli.CommandLineTestCase)
[  139s] ----------------------------------------------------------------------
[  139s] Traceback (most recent call last):
[  139s]   File "/home/abuild/rpmbuild/BUILD/yamllint-1.14.0/tests/test_cli.py", line 416, in test_run_auto_output_without_tty_output
[  139s]     self.assertEqual(err, '')
[  139s] AssertionError: "/usr/lib64/python3.7/site-packages/yaml/[214 chars]):\n" != ''
[  139s] - /usr/lib64/python3.7/site-packages/yaml/constructor.py:126: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
[  139s] -   if not isinstance(key, collections.Hashable):
[  139s] 
```

It can be seen currently on https://build.opensuse.org/package/show/home:jayvdb:coala:python3-bears/python-yamllint , but OBS doesnt keep old logs so it may turn green on the next build.

**Comment by adrienverge** [comment]
Hey @jayvdb, thanks for the report. I experience the same, and hope [PyYAML](https://github.com/yaml/pyyaml) will fix it upstream!

**Comment by jayvdb** [comment]
If your use of pyyaml's code which triggers this is in one specific place, you could use warnings module to disable the deprecation warning occurring while invoking that bit of pyyaml.

Alternatively, maybe disable this test on py3.7 until pyyaml has done their thing?

**Comment by adrienverge** [comment]
Currently there are multiple tests that output warnings (including the one that you reported), but none prevent tests from passing on Travis, nor on my computer.

I'm not very familiar with openSUSE, but I suggest applying a patch (to delete the test) when building the package. Could that be an option? I often have to do it for RPM packaging.

By the way, good news: [this comment from a PyYAML maintainer](https://github.com/yaml/pyyaml/pull/212#issuecomment-458360696) says it should be fixed and released in February :+1:

**Comment by jayvdb** [comment]
I've already skipped this one test, and the update is pending at https://build.opensuse.org/request/show/674874

**Comment by jayvdb** [comment]
Fixed upstream
