### ISSUE TITLE
Please help me with correct ruleset

### ISSUE THREAD

**Issue by gakhrejah** [adrienverge/yamllint#166]
Hi Team,

Yamllint is a great utility.
I need to lint my yaml files but i am getting the error of indentation .
Please find my rules set and yaml file attached.
I need to keep indentation of my yaml file as "2" and it its there it should give me exit code as zero.
If the indentation of my yaml file is not "2" then it should give non zero exit code .

Please help me with the correct rule set. Please let me know if its possible or `not`

Thanks 
[yaml.zip](https://github.com/adrienverge/yamllint/files/2967080/yaml.zip)

**Comment by adrienverge** [comment]
Hi,

Have you looked at the [documentation](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.indentation) about indentation?

**Comment by adrienverge** [comment]
No answer after 1 year, closing.
