### ISSUE TITLE
Rule: Consistent string value style

### ISSUE THREAD

**Issue by mcandre** [adrienverge/yamllint#176]
YAML offers three different syntaxes for string values: raw literals without any quotes, single quotes, and double quotes. Each has advantages and disadvantages.

For example, raw strings often accidentally resolve to nonstring types, when they happen to match certain patterns. This can happen with strings comprised of digits, a decimal point, and further digits. For humans reading a YAML file, that wouldn’t matter much. Or for weakly typed languages. However, strongly typed programming languages tend to generate type errors with these raw strings, once the intermediate structure presents type mismatches with the final marshaling structure. So raw string values in YAML are best avoided. Perhaps a new rule for yamllint could allow for any string syntax / be disabled by default.

Single quoted strings in YAML unfortunately use an obtuse escape notation. This involves using multiple consecutive quotes as opposed to C style backslash notation. More experienced programmers are actually more likely to make a mistake here, as they will be used to backslash escapes, which resolve in surprising ways with this single quoted string syntax for YAML files. On the other hand, single quotes don’t require a Shift modifier (at least on US keyboards) and so are easier on fingers. Anyone who really prefers YAML single quotes, could configure this rule to prefer that all their strings be single quoted.

Finally, double quoted strings in YAML are processed with backslash semantics similar to C, and so are both protected from mistyped interpretation as well as accidental unescaped content. I would propose that string values in YAML always be double quoted, for safety and consistency.

I think YAML also allows for different types as keys, so the same kind of rule for value style could be applied to keys as well. Ideally, these could be configured as matching or even divergent policies.

Regardless of your personal favorite, I think it would improve readability for our users to have a customizable, consistent style to their YAML strings. So.

**Comment by adrienverge** [comment]
Thanks for this comprehensive and interesting summary.

The [quoted-strings rule](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.quoted_strings) allows users to choose whether they'd like to enforce none, single, double quotes (for values only, not for keys). Is this something that could be helpful here?

**Comment by adrienverge** [comment]
No answer after 11 months, closing.
