### ISSUE TITLE
line-length default severity level too high

### ISSUE THREAD

**Issue by direvus** [adrienverge/yamllint#184]
In the default configuration, the 80 character line-length rule reports at the 'error' level.

The line-length rule is a highly subjective style preference.  Some people care about this a lot, others not at all.  It might be important in some files but not in others.  I think that the 'error' level is too severe for a default setting.  Lines longer than 80 characters are not forbidden, or even recommended against, by the YAML specification.  AFAICT, the YAML spec doesn't say anything at all about line length.

Including this style preference at the same severity level as genuine structural errors like key-duplicates by default is weird.

I realise that I can disable this rule, or downgrade it to a warning, in my own configuration but I think the default config could really be improved by making line-length into a warning, and letting people opt-in to having it at the error level if they want to be dogmatic about line length.

**Comment by adrienverge** [comment]
I agree this is a highly subjective style preference. Some people want it as *error*, others want it as *warning*.

In any case, downgrading it as *warning* now would be a breaking change, and many users would disagree with the motivation, and complain about having to change their conf file.

PS: About the the YAML spec, it doesn't say about line length, but doesn't discourage the usage of trailing white space characters, nor trailing empty lines, nor mixed indentation levels... These rules are subjective developer conventions, also enabled as *errors* in yamllint.

**Comment by direvus** [comment]
I suspected that might be the answer.  Thanks anyway for the reply.
