### ISSUE TITLE
.yamllint.yml

### ISSUE THREAD

**Issue by mcandre** [adrienverge/yamllint#190]
Hey, can we support the configuration filename `.yamllint.yml`? This helps text editors to syntax highlight better, and ensures that we are using properly linted configuration files as well!

**Comment by adrienverge** [comment]
Hey @mcandre, this sounds reasonable. Contributions are welcome!

I think this can be done easily by editing `yamllint/cli.py` and `docs/configuration.rst`. For backward compatibility, `.yamllint` should be preferred to `.yamllint.yml` if both are present. And `.yamllint.yaml` should be supported as well.
