### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by zapashcanon** [adrienverge/yamllint#20]
Hi,

I already used `yamllint` on my computer and it worked just fine. Today, I tried to used it as part of the CI for a project and get stuck with this error:

```sh
$ yamllint app/ bin/ ci/ scripts/ src/ var/ web/ .gitlab-ci.yml .yamllint
Traceback (most recent call last):
  File "/usr/bin/yamllint", line 9, in <module>
    load_entry_point('yamllint==1.3.2', 'console_scripts', 'yamllint')()
  File "/usr/lib/python3/dist-packages/yamllint/cli.py", line 119, in run
    for problem in linter.run(f, conf):
  File "/usr/lib/python3/dist-packages/yamllint/linter.py", line 220, in run
    content = input.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3982: ordinal not in range(128)
ERROR: Build failed: exit code 1
```

See the [complete build](https://gitlab.com/zapashcanon/lldc/builds/4378519) for details.

I found a similar bug [here](https://bugzilla.redhat.com/show_bug.cgi?id=971973) and [the commit](https://github.com/zdohnal/system-config-printer/commit/c346c2f) which solved it upstream.

So, I don't know if I'm missing something in my build or if `yamllint` needs to be fixed, thus, I'm opening this issue hoping you'll know what's going wrong here.

Thanks. :)

**Comment by adrienverge** [comment]
Hey @zapashcanon,

This is not a yamllint problem, but a system default encoding problem. You can check it easily by running:

```bash
# This works fine on any system with UTF-8 installed (i.e. almost every system)
$ python3 -c "open('src/LLDC/Bundle/Resources/translations/abilities.fr.yml').read()"
```

```bash
# This fails
$ export LC_ALL=en_US.iso885915
$ python3 -c "open('src/LLDC/Bundle/Resources/translations/abilities.fr.yml').read()"
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1241: ordinal not in range(128)
```

It seems that the default encoding on gitlab build system is not UTF-8.

Can you try `sudo locale-gen en_US.UTF-8`, `export LANG=en_US.UTF-8` and/or `export LANG=C.UTF-8` in your .gitlab-ci.yml?

**Comment by zapashcanon** [comment]
I alreay tried with `LANG=en_US.UTF-8` but not with `LANG=C.UTF-8` and... [it worked](https://gitlab.com/zapashcanon/lldc/builds/4380641) ! :)

Thanks.

**Comment by adrienverge** [comment]
You're welcome :)
