### ISSUE TITLE
Go edition?

### ISSUE THREAD

**Issue by mcandre** [adrienverge/yamllint#206]
As a DevOp, I would like a Go edition of yamllint, in order to reduce the size and complexity of the runtime environment when linting YAML files, as well as dynamically configure linting via Go library function calls.

One way to accomplish this, would be to begin isolating the yamllint configuration and rule set from its default Python implementation, into a programming language agnostic standard, similar to how EditorConfig works. That way, people using Python or Go or Java or Ruby or whatever, can benefit from the essential yamllint core idea, without being locked into software stacks. What do you think?

**Comment by gregswift** [comment]
As a random passer by... that seems out of scope? If you don't want to deal with initiating the python environment to use the tool, just use a [docker image](https://hub.docker.com/r/cytopia/yamllint)?  We are a javascript house and I've been adding this to our makefiles

```
lint-yaml:
    docker run --rm -i -v $(PWD):/data:Z cytopia/yamllint:latest /data/yamls/
```

**Comment by 030** [comment]
See also https://github.com/cytopia/docker-yamllint

**Comment by adrienverge** [comment]
Yamllint was developed in Python for simplicity and because there aren't high performance requirements. It seems irrealistic to me to recode it in Go or Java or Ruby or whatever.
