### ISSUE TITLE
Disabling a rule with a comment has no effect

### ISSUE THREAD

**Issue by durgaswaroop** [adrienverge/yamllint#207]
I have a long line in my yaml file that is 110 characters long.  I have disabled the line-length check for that line with `# yamllint disable-line rule:line-length` at the end of the line.
But when I run the yaml lint, it still comes up as an error. 
How can I remove it just for that line?

```
 % yamllint .gitlab-ci.yml
.gitlab-ci.yml
  1:1       warning  missing document start "---"  (document-start)
  4:1       warning  comment not indented like content  (comments-indentation)
  11:111    warning  too few spaces before comment  (comments)
  47:81     error    line too long (91 > 80 characters)  (line-length)
  75:119    warning  too few spaces before comment  (comments)
```

**Comment by adrienverge** [comment]
Can you please provide an example, e.g. the problematic part of your file `.gitlab-ci.yml`?

Does it have the same format as is https://yamllint.readthedocs.io/en/stable/disable_with_comments.html#disabling-checks-for-a-specific-line?

**Comment by durgaswaroop** [comment]
Surprisingly, I am not getting that error anymore. I am not sure what changed as I have not touched the code the code in the past 3-4 days. But as it is over, I am closing the ticket for now. 
Thanks for the help.
