### ISSUE TITLE
Feature request: auto-fix issue on parsable YAML files

### ISSUE THREAD

**Issue by nmiculinic** [adrienverge/yamllint#209]
I've searching online for yaml formatters, but couldn't find any whose output satisfy the yamllint. Thus it would be great that yamllint also offers fix option for parsable YAML files, at least where it's easy doing so. For example:

```
  1:1       warning  missing document start "---"  (document-start)
```

quite easy to fix. Just add the `---` 

```
  25:1      error    wrong indentation: expected 2 but found 0  (indentation)
```

if the document is parsable, then fixing indentation is easy as well.

**Comment by adrienverge** [comment]
Hi @nmiculinic, is it a (better written) duplicate of #62?

**Comment by nmiculinic** [comment]
Yes
