### ISSUE TITLE
UnicodeEncodeError on 1.19.0

### ISSUE THREAD

**Issue by fengzixu** [adrienverge/yamllint#216]
Traceback (most recent call last):
  File "/usr/local/bin/yamllint", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.5/dist-packages/yamllint/cli.py", line 175, in run
    problems = linter.run(f, conf, filepath)
  File "/usr/local/lib/python3.5/dist-packages/yamllint/linter.py", line 237, in run
    content = input.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 346: ordinal not in range(128)

**Comment by adrienverge** [comment]
Without any explanations or input file example, it will be hard to help you. Please reopen with useful details to reproduce, if you want.

**Comment by fengzixu** [comment]
https://github.com/dragonflyoss/Dragonfly/blob/90c1c3ed5e2f85ffbc5da65dabf1668e4b56f61c/docs/config/dfdaemon_config_template.yml

**Comment by fengzixu** [comment]
@adrienverge please reopen it.

**Comment by adrienverge** [comment]
The file at the provided URL is linted correctly for me.

Please provide details about your problem, and instructions on how to reproduce, otherwise nobody will be able to help you.
