### ISSUE TITLE
Only first indentation error in block mapping is shown

### ISSUE THREAD

**Issue by Kotarski** [adrienverge/yamllint#222]
With config:
```
indentation: { spaces: 2, indent-sequences: true }
```

```
blah:
   - one
   - two
```

Expected:
```
  2:4       error    wrong indentation: expected 2 but found 3 (indentation)
  3:4       error    wrong indentation: expected 2 but found 3 (indentation)
```

Got:
```
  2:4       error    wrong indentation: expected 2 but found 3  (indentation)
```

**Comment by Kotarski** [comment]
For context: I'm trying to implement autofix for indentation errors, but because not all problems are listed it's a lot more difficult

**Comment by adrienverge** [comment]
This behavior is actually intended, first to reduce useless verbosity, and also because 2nd, 3rd, etc. items HAVE to have the same indentation as the 1st item, i.e. their indentation is always correct. Said differently,

```yaml
blah:
   - one
  - two
```
is not valid YAML.

**Comment by Kotarski** [comment]
That's all very reasonable, but it makes the output very difficult to process automatically.

Since there is already a parsable format, this must be considered a use case?

Perhaps a configuration or command line option?

**Comment by adrienverge** [comment]
I understand what you mean but don't feel that it's really needed... Moreover, it would create other understanding issues, for instance:
```yaml
blah:
  - >
      This text (lines 3-4) is correctly indented (from `>`) but badly indented
      because line 2 is. Should lines 3 and 4 be reported by yamllint?
```

About your particular use-case, why not treating all items of a list as badly indented, when the first one is?

**Comment by Kotarski** [comment]
To first point: I guess it depends... to me if indentation is set to a certain value in the config then anything indented differently is wrong based on that value regardless of it's position in a list. Depends what you are comparing against.

Issue for my use case is that the tool is agnostic to the content of the lines (and to other lines) you just tell it what to remove and what to add. To know which lines were in the block I would need to reparse the file.

**Comment by adrienverge** [comment]
As previously said, this is by design. Feel free to reopen if you'd like to continue discussion.
