### ISSUE TITLE
Write file formatted like yamlfmt

### ISSUE THREAD

**Issue by jomach** [adrienverge/yamllint#231]
There is a tool yamlfmt which seems to be pretty old (https://pypi.org/project/yamlfmt/) 
The yamllint discovers more rules then the yamlfmt but it does not allow to fix the file. 

We should add a flag --w for overwriting the file with a proper formatting.

**Comment by adrienverge** [comment]
Is it a duplicate of #209, #62 and #230?

**Comment by jomach** [comment]
yeah of #62. Sorry
