### ISSUE TITLE
'truthy' rule throws false positives on keys named `on`.

### ISSUE THREAD

**Issue by Ferroin** [adrienverge/yamllint#232]
I suspect it will do the same for keys with other names that it would normally warn for if they were values, but `on` is the issue here as it's actually used as a key name in a number of common tools that use keys with the name `on` (notably, GitHub Actions use this key to control when a workflow runs).

Ideally, yamllint should only be looking at the values and not the names of keys for this check.

**Comment by adrienverge** [comment]
A 15-second search would have lead you to https://github.com/adrienverge/yamllint/issues/158.
