### ISSUE TITLE
No changes are reflected in yaml file even after running yamllint

### ISSUE THREAD

**Issue by BharthishAthreya** [adrienverge/yamllint#237]
Hello, 
Im trying to run yamllint for yaml files to make it look more readable and tidy. 
I did pip install yamllint and then try to run something like 
**yamllint filename.yaml**
But that doesn't seem to work. No changes are done to yaml even after running lint. 
Please let me know where am i going wrong or is there any other step which i have missed.

Attaching screenshots for more info
![running_lint](https://user-images.githubusercontent.com/15611058/77043864-63708580-69e4-11ea-98f6-2ac45cb93788.PNG)
![before_lint](https://user-images.githubusercontent.com/15611058/77043867-653a4900-69e4-11ea-8a36-64845dde2b68.PNG)

**Comment by adrienverge** [comment]
Hello,

I'm not sure I understand your problem, could you explain what you expect?

Please note that yamllint is a *linter*: it reports errors, but does not fix them.

**Comment by BharthishAthreya** [comment]
oh, mybad! sorry, Is there any way where i can validate/make yaml readable? Any python module available? I didn't find any in PyPi.

**Comment by adrienverge** [comment]
> I didn't find any in PyPi.

I'm not sure you really searched.

There are some, I don't remember their names, but I'm sure if you search you'll find.

**Comment by BharthishAthreya** [comment]
Thank you!

**Comment by ssbarnea** [comment]
I guess the user wanted a formatter like python black but almost always linters are not also formatters.

I would also like to have a formatter, but considering that YAML is very relaxed in its style finding a common ground would be a real challenge.
