### ISSUE TITLE
Json-Output

### ISSUE THREAD

**Issue by strowi** [adrienverge/yamllint#243]
Hi,

since we are using gitlab and its codeclimate integration, we really would like json-formatted output.
Would you be willing to accept an MR adding json-output adhering to the codeclimate spec ?

-> https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#output

```json
{
  "type": "issue",
  "check_name": "yamllint",
  "description": "wrong indentation: expected 2 but found 4 (indentation)",
  "categories": "Complexity",
  "severity": "critical",
  "location": {
    "path": "/home/x/y/z/test.yml",
    "positions": {
      "begin": {
        "lines": "12",
        "column": "5"
      }
    }
  }
}
```
Ideally this would include the severity:
```
severity -- Optional. A Severity string (info, minor, major, critical, or blocker) describing the potential impact of the issue found.
```
But this would be a breaking change i guess? Since it's optional it could be left out..

regards,
strowi

**Comment by adrienverge** [comment]
Hello @strowi, have you searched similar issues before opening this one?

**Comment by strowi** [comment]
Hi @adrienverge,

i only found this ~3y old one regarding json? 
https://github.com/adrienverge/yamllint/pull/68

After reading the codeclimate-specs again, it seems, they require every issue to be json, but separate issues by "\0", which is not json-compliant. So i guess this would require a separate codeclimate-format?

**Comment by adrienverge** [comment]
Hi @strowi,

A codeclimate-specific (or *any software*-specific) format won't be accepted here. For JSON output, I propose to continue in #68.

Thanks

**Comment by adrienverge** [comment]
Many could be comparable to the GitHub support. Similarly, we could accept dozens of formats with the same argument. For this reason, there won't be new third-party formats added.

**Comment by gardar** [comment]
In case someone else comes across this issue when searching for gitlab codeclimate/codequality output, I found this project: https://github.com/ProfessorManhattan/codeclimate-yamllint
Which contains [the following script](https://github.com/ProfessorManhattan/codeclimate-yamllint/blob/9078e49f0ecb9f67364daa2ceddfede85024d98b/local/codeclimate-yamllint#L6) to generate codeclimate output 
```
yamllint $CONFIG -f parsable . | awk 'BEGIN {FS = ":" } ;{gsub(/^[ \t]+|[ \t]+$|"/, "",$4); match($4,/^\[(warning|error)\](.*)\((.*)\)$/,a); if(a[1]=="error") {sev="major"} else { sev="minor"}}; {printf("{\42location\42:{\42path\42:\42%s\42,\42lines\42:{\42begin\42:%s,\42end\42:%s}},\42severity\42:\42%s\42,\42check_name\42:\42%s\42,\42categories\42:[\42Style\42],\42type\42:\42issue\42,\42description\42:\42%s\42}\0",$1,$2,$3,sev,a[3],a[2]);}'
```

I had to change it a bit to get valid json from it but I ended up with this:

```yaml
lint:
  stage: lint
  script:
    - mkdir reports
    - >
      yamllint -f parsable . | tee >(awk '
      BEGIN {FS = ":"; ORS="\n"; first=1}
      {
          gsub(/^[ \t]+|[ \t]+$|"/, "", $4);
          match($4, /^\[(warning|error)\](.*)\((.*)\)$/, a);
          sev = (a[1] == "error" ? "major" : "minor");
          if (first) {
              first=0;
              printf("[");
          } else {
              printf(",");
          }
          printf("{\"location\":{\"path\":\"%s\",\"lines\":{\"begin\":%s,\"end\":%s}}," \
                 "\"severity\":\"%s\",\"check_name\":\"%s\",\"categories\":[\"Style\"]," \
                 "\"type\":\"issue\",\"description\":\"%s\"}",
                 $1, $2, $3, sev, a[3], a[2]);
      }
      END { if (!first) printf("]\n"); }' > reports/codequality.json)
  artifacts:
    when: always
    paths:
      - reports
    expire_in: 1 week
    reports:
      codequality: reports/codequality.json
```




> Many could be comparable to the GitHub support. Similarly, we could accept dozens of formats with the same argument. For this reason, there won't be new third-party formats added.

How about [going the same route as flake8](https://flake8.pycqa.org/en/latest/internal/formatters.html) and offloading the formatters to plugins?
for example: https://github.com/awelzel/flake8-gl-codeclimate

**Comment by pschichtel** [comment]
Since I found this via google, what I'm using for other tools: https://github.com/tomasbjerre/violations-lib

it even has the yamllint support documented for `--format=parsable`.
