### ISSUE TITLE
[question] Where is yamllint installed?

### ISSUE THREAD

**Issue by rockerdaddy** [adrienverge/yamllint#260]
Following the documentation, I installed via pip, and then attempted to run it as suggested under 'basic usage':

> $ yamllint
> -bash: yamllint: command not found
> 

Obviously this command is not in my path. But searching my system, I do not find the command anywhere. site-packages has a yamllint subdir, but that also does not have this command.

 Where is the 'yamllint' command located?

**Comment by adrienverge** [comment]
It depends on many things; can you give more informations? Your system, the command you use to install yamllint, what this commands said, what does `$PATH` contain, etc.

**Comment by rockerdaddy** [comment]
Cygwin on Windows 10
python -m pip install --user yamllint
Python 3.8.2

 ...and uninstalling so I can reinstall to answer this question shows a binary installed in %HOME%\AppData\Roaming\Python\Python38\scripts.

Problem solved. Cheers :-)
