### ISSUE TITLE
add contribution instructions

### ISSUE THREAD

**Issue by ssbarnea** [adrienverge/yamllint#263]
Apparently there is no documentation about how to contribute to the project, chat or mailing list and maybe more important about how to perform testing.

For a Python project I was surprised not to see a tox file, which could have addressed the lack of testing information quite well.

Users can guess some stuff by looking at the travis config but that gives very poor reproducibility, for example running `flake8` locally gives very different results than on travis, same applies to running tests (huge number of `W504 line break after binary operator` errors)

I think that using tox would be highly desirable for easing the contributions, and also very easy to add.

**Comment by adrienverge** [comment]
@ssbarnea you're right about contribution instructions, I'll add that.

I'm not in favor of adding `tox` config or any other config, because I want tests to be runnable by anybody (from outside the Python ecosystem), without having to install dependencies or read extra documentation.
