### ISSUE TITLE
BUG: quoted-strings only-when-needed with hashtag

### ISSUE THREAD

**Issue by sergey-alekseev** [adrienverge/yamllint#271]
Setup
---

_test.yml_:
```yaml
---
hashtag: 'Test #hashtag'
```

_.yamllint.yml_:  
```yaml
extends: default

rules:
  quoted-strings:
    required: only-when-needed
```

Result
---

```
$ yamllint test.yml 
test.yml
  2:10      error    string value is redundantly quoted with any quotes  (quoted-strings)
```

**Comment by adrienverge** [comment]
Hi Sergey,

Thanks for reporting this. I confirm the bug.

**Comment by julienfalque** [comment]
The issue also happens with values that would be parsed as octal values:

```yaml
foo: '0123456789'
```

**Comment by perlpunk** [comment]
@julienfalque that's not an octal value. note the `9` ;-)

**Comment by julienfalque** [comment]
I don't know what the YAML spec says about this, but when I test using such value, it *is* parsed as an octal value.

Also `yamllint` reports it as a forbidden implicit octal value:
```
  1:16      error    forbidden implicit octal value "0123456789"  (octal-values)
```

**Comment by perlpunk** [comment]
> I don't know what the YAML spec says about this, but when I test using such value, it _is_ parsed as an octal value.

```
Python 3.6.4+ (default, Feb 12 2018, 08:25:03) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> yaml.safe_load("0123456789")
'0123456789'
>>> yaml.safe_load("01234567")
342391
```

**Comment by perlpunk** [comment]
> Also `yamllint` reports it as a forbidden implicit octal value:

Then *this* sounds like a real bug :)

**Comment by julienfalque** [comment]
See #316 and #318 :)

**Comment by adrienverge** [comment]
Thanks for fixing the bugs you discovered @julienfalque :+1:
