### ISSUE TITLE
Enabling parsable output should not be mutually exclusive with colored mode

### ISSUE THREAD

**Issue by ssbarnea** [adrienverge/yamllint#272]
Parsable format (aka pep8) has being the most popular linting output for years. Still, enabling it with yamllint disables the coloring, which does penalize users for no good reasons.

Color support is not the same thing as output format. Please allow us to make format parsable while not disabling the coloring.

**Comment by adrienverge** [comment]
Hello,

Currently yamllint provides a standard, human-readable, potentially colored format. This is the main output format.
The `parsable` format was then added, but is designed for machines only. I'm not sure there are many users that would like a custom parsable-but-colored format.

**Comment by jgstew** [comment]
I would use parsable and color output personally.
