### ISSUE TITLE
No vscode extensions supporting yamllint

### ISSUE THREAD

**Issue by ssbarnea** [adrienverge/yamllint#273]
Sadly there is no vscode extension available for using yamllint, which is quite sad as vscode become most popular non-terminal editor.

We should either do one of these:

- add yamllint support for another linting extension
- write an extension (easier that it appears)
- document a way to enable support for it

**Comment by ssbarnea** [comment]
I proposed adding support https://github.com/redhat-developer/yaml-language-server/issues/262 which is the backend used by https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml one of the most popular vscode extensions.

**Comment by adrienverge** [comment]
Thanks for documenting this @ssbarnea. I'll close because this is not directly related to yamllint, but you have my encouragement to write an extension for your favorite editor :+1:

**Comment by ssbarnea** [comment]
My hope was to avoid writing a new extension due to maintenance issues. I still hope that we could add it as an option of an already existing one.

**Comment by ssbarnea** [comment]
Some time passed and in meanwhile I published https://marketplace.visualstudio.com/items?itemName=zbr.vscode-ansible which runs ansible-lint and yamllint too inside vscode. I may not suit every yamllint user as you need to install ansible-lint too (which brings ansible), but if you do not mind, that will also display results from yamllint as well.

**Comment by arahatashun** [comment]
I found fnando.linter supports yamllint.
https://marketplace.visualstudio.com/items?itemName=fnando.linter

**Comment by kcmr** [comment]
Hi! 👋 Just wanted to share that I recently published a [VS Code extension](https://marketplace.visualstudio.com/items?itemName=kuscamara.yamllint-fix) that integrates yamllint and yamlfix to provide both linting and auto-fix support for YAML files directly in the editor.

It runs yamllint on save and shows issues in the Problems panel, and optionally applies fixes using yamlfix.

Disclaimer: I’m the author of this extension and I’d love to hear any feedback from the community — especially around how it behaves with different .yamllint configurations.

Hope it’s helpful! 😊
