### ISSUE TITLE
Add pre-commit-hook as github topic on this repository 

### ISSUE THREAD

**Issue by ssbarnea** [adrienverge/yamllint#278]
In order to advertise the fact that yamllint is also working as a pre-commit hook, please add `pre-commit-hook` topic to this repository.

By doing this, yamllint will become visible on https://github.com/topics/pre-commit-hook page.

**Comment by ssbarnea** [comment]
@adrienverge Fixing this would take like 10 seconds, but can only done by you: go to https://github.com/adrienverge/yamllint, press the cogwheel from the right side of the screen and add "pre-commit-hook" among the other 4 existing topics. Thanks.

**Comment by adrienverge** [comment]
I don't see the need to add new topics, unless they are *directly* related. Please reopen if you have real arguments for adding `pre-commit-hook` but not `travis`, `circleci`, `python` and others.

**Comment by ssbarnea** [comment]
My intention was to make it easier to pre-commit tool users to discover which linters natively support to be called by it. That can easily be exposed via the proposed topic but if you do not want the additional exposure, no problem. I do not see how the other mentioned topics would make sense to the project.
