### ISSUE TITLE
Yamllint cannot work with yaml file language japanese on Window OS

### ISSUE THREAD

**Issue by tinhhandsome** [adrienverge/yamllint#295]
.\test\jsonforms_data.yml
'charmap' codec can't decode byte 0x81 in position 83: character 
maps to <undefined>
You can fix it according to this link:
https://github.com/tinhhandsome/yamllint/commit/6d1e49dac3ae345ec4b029bd72fea9cf22421cfe

**Comment by adrienverge** [comment]
@tinhhandsome it's hard to understand your problem without context nor examples, but it looks like a duplicate of https://github.com/adrienverge/yamllint/issues/238, isn't it?

**Comment by trinhcanhphuc** [comment]
I think he got this issue when he run yamlint on windows os.
