### ISSUE TITLE
yamllint is now installed by default in GitHub actions virtual environments

### ISSUE THREAD

**Issue by yvele** [adrienverge/yamllint#300]
Just to let you know that yamllint is now installed by default in GitHub actions virtual environments

See https://github.com/actions/virtual-environments/issues/1142 🎉 

This may be helpful to be mentioned in the docs

**Comment by adrienverge** [comment]
Thanks @yvele, good news!

Unfortunately this relies on the `.deb` package, which is not actively maintained. The installed version is 1.10.0, whereas the latest is 1.24.2 (it has lots of bugfixes and new features).

Do you know if it's easy to switch to `pip` on GitHub actions?

**Comment by yvele** [comment]
Yep I've noticed that the yamllint version on GitHub actions is 1.10.0 🤔 

Unfortunately in my issue I suggested using `apt get`.. I didn't know that `.deb` package was so out to date... see https://github.com/actions/virtual-environments/pull/1319/files

We have 2 options:
 - Update `.deb` 
 - Open an issue in https://github.com/actions/virtual-environments about using `pip` instead of `apt get`

What do you think?

**Comment by adrienverge** [comment]
I'm for using `pip`: even if someone dedicates time to actively maintain the deb package, it will always be late compared to the PyPi version (which is pushed a few seconds after a release is created).

**Comment by ssbarnea** [comment]
@yvele You are much better switching to wheels instead of system packages. System ones are always outdated, even those that have active packagers they lack behind, sometimes with years. For pure-python packages, wheels are the way.

**Comment by yvele** [comment]
I've filled an issue in the GitHub Actions virtual environments repo https://github.com/actions/virtual-environments/issues/1657 😉

**Comment by yvele** [comment]
yamllint is installed properly on GitHub Actions 👏  https://github.com/actions/virtual-environments/issues/1657#issuecomment-717953802

**Comment by adrienverge** [comment]
Thanks @yvele!
