### ISSUE TITLE
Make document-start rule disabled by default

### ISSUE THREAD

**Issue by ssbarnea** [adrienverge/yamllint#302]
I have being using and promoting use of yamllint for a good number of years I am still to find a project that really needed to check for the presence of `---` aka `document-start` separators.

I even asked the YAML Spec team and they told me that this is needed unless someone wants to host multiple documents in the same stream/file, something I never seen needed in practice. Even the spec is relatively clear about how optional it is: https://yaml.org/spec/1.2/spec.html

If `---` is required by default, why not also adding the `...` as required? Clearly it will drive everyone insane ;)

This is why I propose disabling this rule by default so the linter would be able to provide useful feedback even without having to reconfigure it.

The default set of rules is quite sensitive as it is supposed to indicate best practices, and inspire people to seek style consolidation instead of opposite where everyone is customizing their rules to the extend that make contributing harder.

**Comment by adrienverge** [comment]
Changing a default configuration in yamllint would break behavior in processes (e.g. continuous integration) for many users and companies, hence it is not an option to consider now.

Whether `---` markers are useful or not isn't really linked to yamllint, but to the YAML spec.
(Just one) example usage of `---`:  https://docs.drone.io/pipeline/configuration/#graph-execution

---

More generally @ssbarnea you've posted dozens of messages in this repository, sometimes out of scope, and you rarely respond to the answers I take time to write. Or even close your issues. Most of the time you don't even answer the questions I ask relative to your new posts.

Before posting new issues (and this one is relevant), please have the respect to stop "abandoning" the old ones you created, especially when someone took the time to read you and follow up with questions. To be honest I would appreciate a bit less "noise".

**Comment by ssbarnea** [comment]
I guess that name of the violation (document-start) confuses us. I was referring to the fact that missing `---` at the start of the file should not trigger `document-start` issue. Requiring it just because some files could need it, does make many of them question the benefits of adoption (not myself, I got sold long time ago).

Even your example contains a yaml example that requires document separator. I never wanted to disable the rule itself, use of `---` is mandatory when having multiple documents. Still, it is never a requirement for single documents. My issue is about not requiring `---` at the start of the files. Most files I encountered are some sort of configuration files which do not support multi-document (makes no sense), requiring them to add "---" makes little sense.

I guess you will ask: how I am going to detect a document that really needs the separator? I think that detecting the presence of a duplicate key at the root level could be an indication of a possible missing "---".

I know that a change in behavior requires major version change and requires a lot of planning. Still if valid it can wait until a major change is needed.

PS. I will revisit all my tickets today.

**Comment by perlpunk** [comment]
> I even asked the YAML Spec team and they told me that this is needed unless someone wants to host multiple documents in the same stream/file,

You probable meant "this is *not* needed unless".

I consider myself a member of the current "Spec team". And yes, it is not "needed" unless you have multiple documents (or a YAML directive), but
* for certain cases like top level scalars it might be mandatory in the next YAML version
* "not needed" doesn't mean "should not be used".

Imagine perl or bash scripts that are not executables. They will ony be called via `perl foo.pl` or `bash foo.bash`. Still, it's a good thing if you add a shebang.

I personally like adding `---` on top of my YAML documents, and in my opinion, the yamllint default is good.

> something I never seen needed in practice.

I did.

**Comment by perlpunk** [comment]
> I guess you will ask: how I am going to detect a document that really needs the separator? I think that detecting the presence of a duplicate key at the root level could be an indication of a possible missing "---".

I don't understand that. Why would a duplicate key indicate that a `---` is missing?

**Comment by ssbarnea** [comment]
@perlpunk If someone is missing to add --- separator between two documents, they will likely endup with duplicate keys.

I think is time to move discussion to YAML spec, I think that https://github.com/yaml/yaml-spec/issues/73 maybe be the right ticket for that.

**Comment by ssbarnea** [comment]
I will also close this issue because I doubt yamllint can do anything before we have YAML Spec team make a decision.
