### ISSUE TITLE
Consider swapping travis for github actions

### ISSUE THREAD

**Issue by ssbarnea** [adrienverge/yamllint#306]
I seen today that more than an hour after I create a pull-request travis was still not reporting and now even allowing me to click the link to see what happens. See below:

![example](https://sbarnea.com/ss/Screen-Shot-2020-08-20-10-30-23.41.png)

Considering that the CI/CD setup of yamllint is very simple, I wonder if would not make sense to use github-actions instead, as they start instantly and report as separated checks, with clear progress on each.

Over the last year I migrated most of my projects to actions, the only one I did not touch are the unmaintained ones. If you are interested I can raise a PR for that.

**Comment by adrienverge** [comment]
I've already seen this Travis bug on other repos, but I think this is new on yamllint. Can you please report if you see it again? Thanks.

**Comment by adrienverge** [comment]
This repo does not use Travis anymore.
