### ISSUE TITLE
How to override yamllint rule value in sonar-project.properties file?

### ISSUE THREAD

**Issue by mangazey2** [adrienverge/yamllint#324]
Default value for line-length.max is 80.
I'd like to override it in my project in sonar-project.properties file. Say, max should be 120.

So, what line should I add to sonar-project.properties file?

**Comment by adrienverge** [comment]
Hello,

I don't understand your question, I don't know what sonar-project.properties is, but I advise you to read the documentation: it's clear and contains all you need to know to change rule options: https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.line_length

Feel free to reopen if you have a question *linked to yamllint*, and that is not in the docs.

**Comment by mangazey2** [comment]
Hi,

Thanks for your answer.
Actually, the question is still not resolved...

sonar-project.properties is a file, containing Sonarqube settings.
For example, its typical content is like the following:
https://github.com/SonarSource/sonar-scanning-examples/blob/master/sonarqube-scanner/sonar-project.properties

So, my question was how to add value of yamllint's rule into this file, in order Sonarqube could read and apply it?

**Comment by adrienverge** [comment]
Hello,

I tried to understand what you ask, but I really couldn't.
It looks like it's related to "Sonarqube", not really to yamllint.
