### ISSUE TITLE
'python setup.py test' is deprecated

### ISSUE THREAD

**Issue by MathieuCouette** [adrienverge/yamllint#328]
When I run the `python setup.py test` command as recommended in the `CONTRIBUTING.rst` file, I get the following deprecation warning:

```bash
root@964ae9d82fd6:/workspaces/yamllint# python setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
```

It appears the command was deprecated last year (pypa/setuptools#1684) and might soon be completely removed (https://github.com/pypa/setuptools/issues/931#issuecomment-694482786). It may be safe to investigate an alternative like `tox` (#320).

**Comment by adrienverge** [comment]
Hello @MathieuCouette, thanks for the notice.

The problem of pull request #320 is that `tox` itself calls `coverage run --source=yamllint setup.py test`, which calls `python setup.py test` and triggers the deprecation warning. @ssato @MathieuCouette what would you recommend?

**Comment by MathieuCouette** [comment]
Replacing `python setup.py test` with `pytest` seems to work, and looks like the easiest fix to me. This requires `pytest` to be installed, as well as the content of `install_requires` (which can be installed with `pip install .`).

In this situation, the move to `tox` addresses a different problem, which is that the test (development) dependencies currently have to be manually installed. Moving to `pytest` adds yet another bunch of these dependencies.

I don't think `tox` is necessary, but it seems nice. I don't see it as adding another test (development) dependency to be manually installed, but rather as replacing all of them (e.g., `doc8`, `flake8`, `flake8-import-order`, `pathspec`, `pytest`, `pyyaml`, `sphinx`). There are of course other advantages, but I think @ssato already touched on those.

I can leave my comments on the PR, if you want.

P.S.: I come from the Node.js world, and while I've used the language itself before, I am fairly new to Python development. I hadn't heard of `tox` before yesterday. 🙂

**Comment by ssato** [comment]
> The problem of pull request #320 is that tox itself calls coverage run --source=yamllint setup.py test, which calls python setup.py test and triggers the deprecation warning. @ssato @MathieuCouette what would you recommend?

Maybe candidates are nose or nose2 or pytest and pytest is the strongest candidate, I think, because it seems that pytest is much popular than others and used in many oss projects already.

**Comment by adrienverge** [comment]
Thanks for your feedback @ssato and @MathieuCouette. I have created #329 which is, I think, the easiest change to get this fixed.
