### ISSUE TITLE
Detect trailing blank lines at EOF

### ISSUE THREAD

**Issue by perlun** [adrienverge/yamllint#332]
Hi,

It would be really nice if it was possible to detect trailing blank lines at EOF with `yamllint`. It's typically the kind of "noise" you want to avoid in most files when possible.

One way to solve this would be a rule with generic support for a user-defined regex. Then you could just block `\r\r$` to prevent it. But a specific rule to block it would also be fine with me, the regex can be pretty useful in other scenarios though.

**Comment by adrienverge** [comment]
Hello @perlun,

Do you have an example that [`trailing-spaces`](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.trailing_spaces) and [`new-line-at-end-of-file`](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.new_line_at_end_of_file) don't currently solve?

**Comment by perlun** [comment]
`trailing-spaces` says that "Use this rule to forbid trailing spaces at the end of lines." `new-line-at-end-of-file` in turns says "Use this rule to require a new line character (\n) at the end of files". Both of these are great and useful. :+1: 

However, what I am aiming for is to prevent files like this from passing through the linter:

```yaml
foo: bar 

# Note the tree trailing empty lines after this line



```

Many editors can be configured to delete empty trailing blank lines, but for those who don't have their editor configured that way, it would be helpful to be able to catch such mistakes right in the linter.

**Comment by adrienverge** [comment]
Ah, so maybe you're after [`empty-lines`](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.empty_lines)?

When I run yamllint on your example, these empty lines at end of file are correctly reported:
```
  1:1       warning  missing document start "---"  (document-start)
  5:1       error    too many blank lines (2 > 0)  (empty-lines)
```

**Comment by perlun** [comment]
Ah, looks good! The `max-end` option there in [`empty-lines`](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.empty_lines) is exactly what I was looking for. Thanks! :+1: I will close the issue now.

(Thanks for a nice tool btw! :bow:)
