### ISSUE TITLE
All checks have pass successful

### ISSUE THREAD

**Issue by abbaskiko** [adrienverge/yamllint#342]
All checks have pass successful

_Originally posted by @abbaskiko in https://github.com/adrienverge/yamllint/pull/341#issuecomment-719793552_

**Comment by adrienverge** [comment]
Interesting. Thanks!

**Comment by abbaskiko** [comment]
> All checks have pass successful
> 
> _Originally posted by @abbaskiko in [#341 (comment)](https://github.com/adrienverge/yamllint/pull/341#issuecomment-719793552)_

dear adrienverg i am some question about working on etherscan and smart contrat can you help me?
