### ISSUE TITLE
implement default config file detection and loading

### ISSUE THREAD

**Issue by ssbarnea** [adrienverge/yamllint#36]
Like many other tools like pep8, flake8, tox,... this one should also be able to look for the existence of a config file and load it if no other config file is specified from the command line.

I supposed that `.yamllint.yaml` should be a good name.

**Comment by adrienverge** [comment]
Hi @ssbarnea,

Did you take a look at the docs?
http://yamllint.readthedocs.io/en/latest/configuration.html#configuration
