### ISSUE TITLE
Missing filenames in Summary->Annotations in Github Actions

### ISSUE THREAD

**Issue by dsvua** [adrienverge/yamllint#364]
I looked at other tickets and all of them mentions that filenames and line numbers suppose to be in Annotation. However, I do not see them there:
![yamllinter_no_filenames_no_lines](https://user-images.githubusercontent.com/9003215/110023260-f6d8be80-7cfa-11eb-956e-d669aca8bf71.png)

**Comment by dsvua** [comment]
Closing as comments are added in `Files Changed` tab:

![github](https://user-images.githubusercontent.com/9003215/110035129-43c39180-7d09-11eb-9577-9471d08461b6.png)

**Comment by AngrySoundTech** [comment]
I think this is still worth looking at, as warnings an errors from rule changes in PR's don't have an easy way to locate because those files were not changed.
