### ISSUE TITLE
Old version still provided by Ubuntu repository

### ISSUE THREAD

**Issue by boonware** [adrienverge/yamllint#368]
[This issue](https://github.com/adrienverge/yamllint/issues/73) points out that the version provided by Ubuntu package repository is old. Over three years later this has still not been addressed. I have installed Yamllint on Ubuntu and gotten the same outdated version. The above ticket was closed stating that " I agree this issue is not relevant, since the Ubuntu package is not maintained here.", however I disagree with this assessment considering users are still encountering the same problem years later. The Ubuntu package repository needs to be updated. Even if the repository is not maintained here, I believe at this stage the project has the responsibility to at least figure out how to get this addressed. The old version of Yamllint on Ubuntu is known to have bugs such as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=860075.

**Comment by adrienverge** [comment]
As stated in the issue you're pointing to, we don't maintain packages here. Please contact Ubuntu maintainers.
