### ISSUE TITLE
Add a possibility for default config file path

### ISSUE THREAD

**Issue by TristanDewalle** [adrienverge/yamllint#371]
For now, one of the default config file path is `~/.config/yamllint/config` but as the config file itself is written in yaml, IMHO, it would be a good idea to at least have `~/.config/yamllint/config.yml` as a default path. 

The `yml` extension allowing yamllint to work on this file by default when using yamllint through syntastic for example

**Comment by adrienverge** [comment]
Hello, thanks for the feedback.

Here is my point of view:
- It means adding a new default config path, what I'm opposed to.
- UNIX systems usually detect filetype from content, not from filename or extension. It's very usual to have extensionless files.
- Most text editors also detect filetype from content.
- If there is an extension, it should be `.yaml`, not `.yml`. YML stands for Yahoo Markup Language, which is something else. Same for JSON and `.json` vs. `.jsn`.
