### ISSUE TITLE
`github` output format on Github hides filenames and lineno

### ISSUE THREAD

**Issue by raphael-riel** [adrienverge/yamllint#377]
Using `github` or `auto` output format under GH Actions CI will not show file names or line numbers.
<img width="576" alt="Screen Shot 2021-04-27 at 3 44 20 PM" src="https://user-images.githubusercontent.com/474697/116305726-2d1e4180-a772-11eb-8a93-87dff4552945.png">

Forcing `standard` will yield something usable:
![image](https://user-images.githubusercontent.com/474697/116305670-17108100-a772-11eb-9a66-1c21254b5e64.png)

Using yamllint 1.26.1

**Comment by adrienverge** [comment]
@andrewimeson what do you think?

**Comment by raphael-riel** [comment]
There's some debugging/investigation already done over here about filenames not printed in logs: https://github.com/golangci/golangci-lint-action/issues/119#issuecomment-738355857

**Comment by andrewimeson** [comment]
This is intended, right? The line numbers and filenames are output by yamllint, it's just that GitHub isn't showing them _in that view_. It is annotating the files.

I might be missing something. I think this is working as intended, but perhaps the UX of GitHub Actions could be better to make this obvious

**Comment by andrewimeson** [comment]
This has come up twice before, #364 and #357

Perhaps we should add some documentation to clear up the confusion? Or point to some GitHub Actions docs on finding annotations?

**Comment by andrewimeson** [comment]
I suppose another option would be to change the `github` format to output both. I'm not a fan of that since it would double the amount of logging and make the functionality of the GitHub Actions output odd. What if we added support for passing multiple formats? `yamllint --format github,parsable`

```
::warning file=foo.yaml,line=1,col=1::[document-start] missing document start "---"
foo.yaml:1:1: [warning] missing document start "---" (document-start)
::warning file=test.yaml,line=3,col=8::[truthy] truthy value should be one of [false, no, true, yes]
test.yaml:3:8: [warning] truthy value should be one of [false, no, true, yes] (truthy)
```

**Comment by adrienverge** [comment]
@andrewimeson thanks for taking a look!

> This is intended, right? The line numbers and filenames are output by yamllint, it's just that GitHub isn't showing them in that view. It is annotating the files.

That's also what I thought (but I'm don't really use this output format).
@raphael-riel, do you have a link to the page where your first screenshot was taken?

I don't think support for multiple formats (`yamllint --format github,parsable`) is needed, and it will complicate both usability and maintenance.

> Perhaps we should add some documentation to clear up the confusion? Or point to some GitHub Actions docs on finding annotations?

Yeah why not.

**Comment by raphael-riel** [comment]
@adrienverge Unfortunately it's from a private repo.

Here's a plaintext log of what I get with `output_format=github` on my local setup:
![image](https://user-images.githubusercontent.com/474697/116547862-6fa26400-a8c1-11eb-84fe-9aae3459b6d9.png)
File path is good

Actually, the said annotation doesn't show up in the "Files Changed" view for our PRs. And I can't find any settings in our repo that could "make it active". So the Action's logs are the only way I have right now to know which lint errors yamllint has found.

A) Could it be the leading `./` that makes Github not able to find the corresponding file?
B) I'm running the linter via a Makefile target. But I tried to run yamllint directly from the action, with no success.

Let me try out some debugging around "A", but in the meantime, may I suggest a `github-detailed` output format that will also contains the filename and lineno within the "description" node of the error line? e.g. `::error file=./dbt/poka/dbt_project.yml,line=22,col=6::(./dbt/poka/dbt_project.yml:22:6) [indentation] wrong indentation: expected 4 but found 5`

**Comment by raphael-riel** [comment]
Alright, hypothesis "A" was good. Fix proposed here: https://github.com/adrienverge/yamllint/pull/378

I'm still leaning toward the possibility to have the full filename and lineno in the GH Action's logs somehow so it's presented in a more "compact and portable" format than the annotations.

**Comment by andrewimeson** [comment]
I created a branch to test, and I think it's working even with the leading dots. This is the output if I run it locally (confirming the leading periods):
```sh-session
$ shopt -s extglob
$ yamllint --format github ./*+(.yaml|.yml) ./**/*+(.yaml|.yml)
::warning file=./bad.yml,line=2,col=15::[truthy] truthy value should be one of [false, no, true, yes]
::warning file=./bad_bacon.yml,line=1,col=1::[document-start] missing document start "---"
::error file=./bad_bacon.yml,line=6,col=3::syntax error: expected <block end>, but found '?' (syntax)
::warning file=./with space/bad_bacon.yml,line=1,col=1::[document-start] missing document start "---"
::error file=./with space/bad_bacon.yml,line=6,col=3::syntax error: expected <block end>, but found '?' (syntax)
::warning file=./with space/bad_bacon2.yml,line=1,col=1::[document-start] missing document start "---"
::error file=./with space/bad_bacon2.yml,line=6,col=3::syntax error: expected <block end>, but found '?' (syntax)
```

and it shows up in the [Files Changed tab.](https://github.com/andrewimeson/ci-troubleshooting/pull/2/files)

**Comment by roy-work** [comment]
I'm hitting the bug here, too; warnings emitted, but no filenames.

But it seems like people think this isn't a bug: what am I … missing, here?

I know that it's emitted annotations in the format that Github Actions supports. Still, on our codebase it emits ~200 or so. Some of those end up on the workflow run's "Summary" tab, but definitely not all 200 of them. (I have no idea how Github is picking and choosing.) A filename on the log output would help me understand, for the output in the log, what's going on.

**Comment by andrewimeson** [comment]
@roy-work if you're running yamllint on generated YAML, it'd be better to override the output format. The GitHub Actions Annotations are designed for annotating source-controlled YAML.

If you're linting both source controlled and not source controlled YAML, you could split it into two tasks. It might be more efficient to use `readarray` than do it the way I did with `xargs`, but this would work

```yaml
---
on: push  # yamllint disable-line rule:truthy

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # […]
      - name: Lint version-controlled YAML
        run: |
          git ls-files '*.yaml' '*.yml' |
              xargs yamllint --strict --format github

      - name: Lint generated YAML
        run: |
          git ls-files --others --exclude-standard '*.yaml' '*.yml' |
              # Override the output format since GitHub Actions Annotations
              # presume version-controlled files
              xargs yamllint --strict --format standard
```

**Comment by ReenigneArcher** [comment]
This is still broken, though you can atleast see part of the file path. I thought it was just a bug with the yamllint action I was using, but I just changed to using yamllint from pypi and the issue is the same.

<img width="1015" height="64" alt="Image" src="https://github.com/user-attachments/assets/6b214331-1c39-45d0-aa0a-02f3ad34aa28" />

Anyway, is there anyway to turn off github format? No matter what I pass in to `--format`, the github format is still used. I'd prefer to use my own problem matcher.
