### ISSUE TITLE
Does it support checkstyle-format export

### ISSUE THREAD

**Issue by caryyu** [adrienverge/yamllint#407]
Due to we're using SonarQube as our QA management system, I'd like to know if it supports the export of Checkstyle format after lint because some of the traditional industrial standards are better supported by it

**Comment by adrienverge** [comment]
Hello, I don't know about this format, but you can find all output format using `yamllint -h`. There is also a bit of information about output formats at https://yamllint.readthedocs.io/en/stable/quickstart.html.

I'll close since this is not a bug or issue.
