### ISSUE TITLE
Rules for certain keys

### ISSUE THREAD

**Issue by janosh** [adrienverge/yamllint#411]
How about adding the ability to define rules for certain keys? Say enforce that all `description` keys must not contain repeated spaces and should end with a period?

**Comment by adrienverge** [comment]
You mean something like described in other existing issues, e.g. https://github.com/adrienverge/yamllint/issues/392 and https://github.com/adrienverge/yamllint/issues/404? Or something different?

**Comment by janosh** [comment]
Yes, exactly. Essentially I was suggesting a regex check for certain keys.

Something like

```yaml
keyRules:
  description:
    regex: '.*\.'
```

to enforce all `description` keys end in a period. I'll close this assuming you're stance remains unchanged that this doesn't belong in yamllint.
