### ISSUE TITLE
Why is "too many spaces before/after colon" considered an error?

### ISSUE THREAD

**Issue by kaddkaka** [adrienverge/yamllint#436]
Why is "too many spaces before/after colon" considered an error?

The first example about mappings in the yaml specification uses extra spaces:

https://yaml.org/spec/1.2.2/#example-mapping-scalars-to-scalars

**Comment by adrienverge** [comment]
It's only an error if you decide they should be reported as errors, using the [`colons` rule](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.colons). Similarly, some people like extra spaces at the end of lines, some others like dict keys to be unsorted, others don't use `---` markers. Yet, there are yamllint rules for these use-cases: `trailing_spaces`, `key-ordering` and `document-start`: your call to use them or not.

Here is how to create your own configuration based on what you like: https://yamllint.readthedocs.io/en/stable/configuration.html#extending-the-default-configuration

**Comment by kaddkaka** [comment]
Yes, it's just a strange default I guess.
