### ISSUE TITLE
Enhancement: Only print errors (ignore all warnings)

### ISSUE THREAD

**Issue by kaddkaka** [adrienverge/yamllint#437]
When running the yamllint tool, it's probably more interesting to look at errors first so it would be nice to be able to filter the output to only show errors and ignore warnings.

Instead of this:
```
example.yaml
  1:1       error    too many blank lines (1 > 0)  (empty-lines)
  93:101    warning  line too long (117 > 100 characters)  (line-length)
  106:101   warning  line too long (109 > 100 characters)  (line-length)
```
This would be the output:
```
example.yaml
  1:1       error    too many blank lines (1 > 0)  (empty-lines)
```

**Comment by adrienverge** [comment]
Hello, please take the time to search for existing issues before opening new ones. There is at least this one: https://github.com/adrienverge/yamllint/issues/86. Please reopen if your question is different.
