### ISSUE TITLE
Quote rules support [proposal]

### ISSUE THREAD

**Issue by AdrienFromToulouse** [adrienverge/yamllint#44]
Hi!

Thanks a lot for this project. This is the best YAML linter I got so far. I specially like the Eslint output style!

I was wondering if it would be possible to support some extra rules, like `quote`.
e.g: http://eslint.org/docs/rules/quotes

Indeed I would like to enforce single quote when necessary. May be this requirement would make no sense tho.

Cheers!

**Comment by adrienverge** [comment]
Thanks Adrien!

This is a good idea. Unfortunately I don't have much time to implement it myself, but any contribution towards this would be welcomed.

**Comment by nifr** [comment]
I guess this issue can be closed.

The requested feature is meanwhile present in form of the [quotes_strings](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.quoted_strings) rule.

**Comment by adrienverge** [comment]
Yes, thanks!
