### ISSUE TITLE
Create `junitxml` output

### ISSUE THREAD

**Issue by QuentinN42** [adrienverge/yamllint#441]
On gitlab, test suite must output in junitxml format to be displayed on the UI.

I think I can add a parser to do this.

**Comment by QuentinN42** [comment]
Soo ...
It's more complicated than I thought.
The xml format must have a head and a tail, need a bit of refactor.
I've forked the repo, I open an MR for that.

**Comment by QuentinN42** [comment]
cf. https://github.com/adrienverge/yamllint/pull/442

**Comment by adrienverge** [comment]
Hello,

Like in other similar issues: new third-party output formats (junitxml, SonarQube, checkstyle, codeclimate, etc.) are not likely to be accepted here.

What about writing a tiny wrapper to convert yamllint's output (YAML format, or JSON once it's implemented) to your favorite XML format?

**Comment by QuentinN42** [comment]
I've already done that but it's flaky as f*
