### ISSUE TITLE
Is this a bug in truthy checking ?

### ISSUE THREAD

**Issue by tamere-allo-peter** [adrienverge/yamllint#447]
In the attached screenshot of yamllint's `ci.yaml` the pink dot marks the `on:` line onto which the `# yamllint disable-line rule:truthy` comment was added.

Shouldn't yamllint autmatically ignore lines like this one, where the truthy value is on the left side of the colon, meaning it probably isn't a truthy value after all ?

![ci](https://user-images.githubusercontent.com/85658105/159377801-8858bd40-e856-4079-9704-64f6cf09c05a.png)

Is this expected behavior or a bug please ?

**Comment by adrienverge** [comment]
Hello, I'll close this because the subject is already largely discussed in other issues / pull requests (please search), and there are at least 3 ways to prevent yamllint to report errors on the key `on`.

**Comment by tamere-allo-peter** [comment]
@adrienverge you're right, sorry for this dupe.
