### ISSUE TITLE
Implement yamllint in code

### ISSUE THREAD

**Issue by bpgould** [adrienverge/yamllint#450]
I would like to import the package and pass a file to a function to have it lint the file, without using command line. 

For example,
```
import yamllint
linted_file = yamllint.lint('path/to/file.yaml', config, otherArgs)
```

Can this functionality be exposed in this kind of interface since I am sure this already exists under the hood?

**Comment by andrewimeson** [comment]
@bpgould check out the [docs for the module](https://yamllint.readthedocs.io/en/stable/development.html)
