### ISSUE TITLE
yamllint breaks on some files in yaml-test-suite

### ISSUE THREAD

**Issue by tamere-allo-peter** [adrienverge/yamllint#452]
```shell
$ yamllint --version
yamllint 1.26.3

$ git clone https://github.com/yaml/yaml-test-suite
$ cd yaml-test-suite
$ make data-update

$ yamllint data/4H7K/in.yaml
Traceback (most recent call last):
  File "/home/jerome/.local/bin/yamllint", line 8, in <module>
    sys.exit(run())
  File "/home/jerome/.local/lib/python3.8/site-packages/yamllint/cli.py", line 210, in run
    prob_level = show_problems(problems, file, args_format=args.format,
  File "/home/jerome/.local/lib/python3.8/site-packages/yamllint/cli.py", line 106, in show_problems
    for problem in problems:
  File "/home/jerome/.local/lib/python3.8/site-packages/yamllint/linter.py", line 203, in _run
    for problem in get_cosmetic_problems(buffer, conf, filepath):
  File "/home/jerome/.local/lib/python3.8/site-packages/yamllint/linter.py", line 140, in get_cosmetic_problems
    for problem in rule.check(rule_conf,
  File "/home/jerome/.local/lib/python3.8/site-packages/yamllint/rules/key_duplicates.py", line 87, in check
    context['stack'].pop()
IndexError: pop from empty list
```

Hoping this helps.

**Comment by adrienverge** [comment]
Hello Jérôme, thanks for the report! I didn't know this *YAML Test Suite* project.

So it seems the error appears on this YAML content:
```yaml
---
[ a, b, c ] ]
```

Normally, yamllint should issue a *syntax problem*, not crash. I guess there's some condition to add inside [these lines of `key_duplicates.py`](https://github.com/adrienverge/yamllint/blob/2f423117c1f1e49d115169cd4a5e1722d68fabfe/yamllint/rules/key_duplicates.py#L84-L87), like "if context is not empty". Would you like to contribute?

**Comment by perlpunk** [comment]
Just for the record, the link to https://github.com/yaml/yaml-test-suite :)

**Comment by tamere-allo-peter** [comment]
@perlpunk sorry I should have added the link. Thanks.

@adrienverge I thought about doing just that yesterday but then I wondered about what to do in the case the stack is empty. Not knowing what to do in this case I prefered to simply report the bug for advice. If nothing has to be done in this case then yes I could send a PR, please tell.

**Comment by adrienverge** [comment]
Fixed in commit https://github.com/adrienverge/yamllint/commit/c268a82c5a72921ea3598e745341b23fa7d13e58, thanks to @tamere-allo-peter.
