### ISSUE TITLE
yamllint didn't find an unmatched quotes

### ISSUE THREAD

**Issue by orsenthil** [adrienverge/yamllint#498]
```
---
"key": "value"
"n1":
  - "n2":
    "image": "something
    "n3":
```

$ yamllint ex1.yaml
✔ YAML Lint successful.

$ yamllint --version
1.7.0

**Comment by andrewimeson** [comment]
yamllint 1.7.0 was released in April 2017. The current version is 1.28.0.

```sh-session
$ cat << 'EOF' | yamllint -
---
"key": "value"
"n1":
  - "n2":
    "image": "something
    "n3":
EOF
stdin
  6:6       error    syntax error: expected <block end>, but found '<scalar>' (syntax)

$ yamllint --version
yamllint 1.28.0
```

**Comment by orsenthil** [comment]
Very interesting. I had install yaml-lint using npm and I assumed it will bring the latest version

> 17315  [2022-10-07 04:46:20] npm install -g yaml-lint

I will use the latest version.  Thank you.

**Comment by andrewimeson** [comment]
@orsenthil it looks like you're using a different project. The yamllint here (adrienverge/yamllint) is a Python project. You appearing to be using [rasshofer/yaml-lint,](https://github.com/rasshofer/yaml-lint) a Node project
