### ISSUE TITLE
Publish wheels

### ISSUE THREAD

**Issue by PeterJCLaw** [adrienverge/yamllint#501]
Thanks for providing this great tool.
I can see that in the past wheels have been uploaded to PyPI, however for more recent versions (since at least 1.26.1) only have source distributions.
Would it be possible to upload wheels for the latest version and future versions?

Note that https://github.com/adrienverge/yamllint/pull/25 (while correct at the time) should probably be removed now that this package only supports Python 3. (Universal wheels means the package supports Python 2 & 3 with a single codebase and package).

**Comment by adrienverge** [comment]
Hello Peter,

Sorry about that, I forgot pushing wheels since 1.26.1. I'll try to be more meticulous in the future.
In the meantime, I've pushed the last version (1.28.0) as a wheel on PyPi.

Also I've open https://github.com/adrienverge/yamllint/pull/504 to remove the `universal` flag.

**Comment by PeterJCLaw** [comment]
Would you be open to a PR which moves publication into a GitHub Action? It could be configured to run when you push a tag, so once configured (i.e: secrets added) all you'd need to do each time is push the tag and CI would handle the rest.

**Comment by PeterJCLaw** [comment]
Thanks for adding that wheel!

**Comment by adrienverge** [comment]
You're welcome!

I prefer pushing them manually, it's more straightforward for me and easier to debug in case something goes wrong. Moreover pushing the release is a habit when I create a tag, so it's not a problem.
