### ISSUE TITLE
[feature] Can we add shell completions for bash/zsh/fish/posh/etc?

### ISSUE THREAD

**Issue by Freed-Wu** [adrienverge/yamllint#502]
Thanks!

**Comment by perlpunk** [comment]
You can find completions for bash and zsh here: https://github.com/perlpunk/shell-completions
Disclaimer: it's maintained by myself

**Comment by adrienverge** [comment]
Hello!

Shell completion files and other "meta" files (e.g. packaging) are maintained outside the source code repo.

Thanks @perlpunk for creating one for yamllint!

**Comment by Freed-Wu** [comment]
Why not use <https://docs.iterative.ai/shtab/> as an extra requirement, like <https://github.com/andreafrancia/trash-cli/blob/master/trashcli/shell_completion.py>? Write shell completion scripts manually is complex. Generate them automatically is a better solution.

Thanks.

**Comment by Freed-Wu** [comment]
I have seen <https://github.com/perlpunk/shell-completions/blob/master/specs/yamllint.yaml>. It still need user to write a yaml file manually. If the upstream change command line option, it should be updated to adapt it.

I think generate shell completion script from argparse's Argument may be a more convenient solution. Like <https://docs.iterative.ai/shtab/use/#library-usage>. User can use `XXX --print-completion bash/zsh/tcsh` to generate shell completion script and don't need write any yaml file.

**Comment by perlpunk** [comment]
> I think generate shell completion script from argparse's Argument may be a more convenient solution.

Sure, a valid thing.
Generating completions from a yaml file works for scripts in all languages.
Generating completions from argparse only works for python scripts.

It might be even easier to generate a yaml file from argparse and then pass it to my script ;-)

The goal of my project was to have a common specification format for commandline args (not only for completion).
So far every language writes its own modules to do that, and every module behaves a bit differently and has different features and bugs.

Anyway, that's offtopic I guess...

**Comment by Freed-Wu** [comment]
> So far every language writes its own modules to do that

Right, to the best of my knowledge, python/go/rust all have these tools. However, for this project, I think `shtab` may be a good solution once for all. I want to know if this project can accept a PR like trash-cli or realize it by the maintainer? @adrienverge

**Comment by adrienverge** [comment]
The `yamllint` command-line interface won't likely change in the future, and I prefer avoiding adding a dependency to this project. Hence, I would recommend using the files created by Tina to avoid adding extra code in yamllint.

**Comment by Freed-Wu** [comment]
> avoiding adding a dependency to this project

Even if it is an extra requires? (Even if user don't install it, the program can still work except completion.)
