### ISSUE TITLE
`setup.py` → `pyproject.toml`

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [adrienverge/yamllint#509]
[Configuring setuptools using `pyproject.toml` files](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html)

Plan migration from executable `setup.py` to declarative `pyproject.toml`:

1. Move to `pyproject.toml` and make `setup.py` a thin wrapper
2. Optionally use `setuptools_scm` to automate versioning

Nothing urgent here, just a suggestion to modify at some point.

**Comment by adrienverge** [comment]
> 1. Move to `pyproject.toml` and make `setup.py` a thin wrapper

+1, since this is the new standard.

**Comment by DimitriPapadopoulos** [comment]
Just keep in mind this is relatively new. Installing from source requires recent versions of `pip` and/or `setuptools`, more recent than bundled with Ubuntu 22.04 for example.

See for example https://github.com/codespell-project/codespell/pull/2523.

**Comment by DimitriPapadopoulos** [comment]
Also, it might not be possible to share the following variables any more, between the setup process and the rest of the code, because setup now relies on a declarative `pyproject.toml` instead of the Python script `setup.py`. Will that necessarily result in duplication?

**Comment by adrienverge** [comment]
> Just keep in mind this is relatively new.

Sure. I don't think we should do the transition now.

> Also, it might not be possible to share the following variables any more, [...] Will that necessarily result in duplication?

Well seen. I guess the new "right way to do" is to declare *name*, *version*, *author*, etc. in `pyproject.toml`, and fetch them  from Python code using a setuptools helper.

**Comment by DimitriPapadopoulos** [comment]
Indeed, from [Package Discovery and Resource Access using pkg_resources](https://setuptools.pypa.io/en/latest/pkg_resources.html):
> The `pkg_resources` module distributed with `setuptools` provides an API for Python libraries to access their resource files
he [pkg_resources](https://setuptools.pypa.io/en/latest/pkg_resources.html) module “_provides an API for Python libraries to access their resource files_”.

Also, for those installing from source, having up to date `pip` and `setuptools` is required any way. From [Installing Packages](https://packaging.python.org/en/latest/tutorials/installing-packages/#ensure-pip-setuptools-and-wheel-are-up-to-date):
> While `pip` alone is sufficient to install from pre-built binary archives, up to date copies of the `setuptools` and `wheel` projects are useful to ensure you can also install from source archives:
> ```
> python3 -m pip install --upgrade pip setuptools wheel
> ```
Therefore, my first remark about the need for recent versions is not considered to be an issue. Yet, my short experience is that the package documentation should remind this to end-users who attempt to install from source.

**Comment by DimitriPapadopoulos** [comment]
And a very long text with a funny introduction:
[Why you shouldn't invoke `setup.py` directly](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html)
> I realize that this article is quite long, and unfortunately this is the _short version_. [...] I hope that this article can be useful when you want to advocate against the use of `setup.py`: when you make a PR or a comment in a Slack channel, you can link to this Proustian monstrosity and hope that your audience pales before the prospect of reading through the whole thing and just assents to whatever you're asking them to do.

**Comment by barrelful** [comment]
@adrienverge now I started having an annoying warning from pip:

```
  DEPRECATION: yamllint is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```

Maybe now it is a good time to transition? If you don't want to do it yourself, maybe I can make a PR.

**Comment by staticdev** [comment]
I am using `pyproject.toml` in all my professional projects and also all projects I maintain here on Github. It centralizes configs for the repo and works flawless for me in the past years.

**Comment by DimitriPapadopoulos** [comment]
The downside is that `pyproject.toml` often requires recent versions of `pip`, `setuptools` and `wheel` before installing from source. But then that's what the [Python Packaging User Guide](https://packaging.python.org/en/latest/tutorials/installing-packages/#ensure-pip-setuptools-and-wheel-are-up-to-date) suggests any way.

I won't have time for a PR in the short term.

**Comment by staticdev** [comment]
@DimitriPapadopoulos you don't need.. it is already done https://github.com/adrienverge/yamllint/pull/557

**Comment by ssbarnea** [comment]
@adrienverge Can we please make this a reality, it is a share to read:
```
DEPRECATION: yamllint is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```

**Comment by adrienverge** [comment]
Sure, please see the ongoing discussion at https://github.com/adrienverge/yamllint/pull/557.
