### ISSUE TITLE
[feature] Support PEP518

### ISSUE THREAD

**Issue by Freed-Wu** [adrienverge/yamllint#519]
According to <https://peps.python.org/pep-0621>, any python project should
store its metadata in `pyproject.toml`, not `.gitlint`, `.yamllint.yaml`, `.vintrc.yml`, `addon-info.json`, or other thing.

Many projects have support PEP621, such as

- <https://github.com/psf/black>
- <https://github.com/codespell-project/codespell>
- <https://github.com/PyCQA/pydocstyle>
- <https://github.com/pypa/setuptools>
- <https://github.com/pypa/setuptools_scm/>
- <https://github.com/pypa/hatch>
- <https://github.com/pypa/flit>
- <https://github.com/python-poetry/poetry>
- ...

So I advise this project can support, too.

Before python3.11, toml support must be provided by third-party package, such as

- <https://github.com/psf/black>: [tomli](https://github.com/psf/black/blob/main/pyproject.toml#L70)
- <https://github.com/codespell-project/codespell>: [tomli](https://github.com/codespell-project/codespell/blob/master/pyproject.toml#L46)
- <https://github.com/PyCQA/pydocstyle>: [toml](https://github.com/PyCQA/pydocstyle/blob/master/setup.py#L11)
- <https://github.com/pypa/setuptools>: [tomli, tomli-w, ini2toml](https://github.com/pypa/setuptools/blob/main/setup.cfg#L72-L81)
- <https://github.com/pypa/setuptools_scm/>: [tomli](https://github.com/pypa/setuptools_scm/blob/main/setup.cfg#L35)
- <https://github.com/pypa/hatch>: [tomli-w, tomlkit](https://github.com/pypa/hatch/blob/master/pyproject.toml#L52-L53)
- <https://github.com/pypa/flit>: [tomli](https://github.com/pypa/flit/blob/main/pyproject.toml#L32)
- <https://github.com/python-poetry/poetry> [tomli, tomlkit](https://github.com/python-poetry/poetry/blob/master/pyproject.toml#L70-L72)
- ...

You can use one as extras_require.

After python3.11, tomllib is a builtin package. Not need install any toml package. Remember `python<3.11` in requirements.txt

**Comment by Freed-Wu** [comment]
It should be https://peps.python.org/pep-0518/#tool-table (right, pep only have a number not a name which make it is hard to remember), It suggests every python tool store their setting to pyproject.toml

**Comment by Freed-Wu** [comment]
There are two exceptions:

[codespell](https://github.com/codespell-project/codespell) is a project written by python and it check words which spell wrong in any project (not only python). It support pyproject.toml.

[pyright](https://github.com/microsoft/pyright) is a project written by typescript and it is a linter of python. It support pyproject.toml too.

Is supporting a new config format possible? It will not break the compatibility.

**Comment by adrienverge** [comment]
I'd rather not, because if we support `pyproject.toml` there's no reason for not supporting other languages configuration files.

**Comment by Freed-Wu** [comment]
OK, I see.
