### ISSUE TITLE
Handle linting of yaml templates

### ISSUE THREAD

**Issue by kuwv** [adrienverge/yamllint#547]
Often a lot of yaml is written as templates. It would be nice if yamllint allowed the handling of these files with additional rule sets. This would allow users to help enforce standards.

Some useful rules I can see would be:
- Pre / Post bracket definition. Default to double curly braces
- Pre / Post inner whitespace handler. Default to dash.
- Same curly braces rules sets but customizable for the template.

I understand if you feel this may be out of scope, but I figured I'd try.

**Comment by adrienverge** [comment]
Hello,

To make things clearer, could you post an example of YAML content + the errors you would expect to be reported?

If you're referring to templates like Jinja2 / Liquid / Twig / etc., beware that YAML parsers fail to interpret such files, so it seems complicated. See #61, #65, #128, #311, #408, #460, #462, #507, #531...

**Comment by kuwv** [comment]
I am aware of this. Ansible with Jinja2 works great but, helm not so much. An LSP might be a better choice for that type of parsing but that would be out of scope of yamllint in it's current form.
