### ISSUE TITLE
yamllint 1.8.0 no longer works with python 2.6

### ISSUE THREAD

**Issue by mattclay** [adrienverge/yamllint#55]
Now that `yamllint` requires `pathspec` as of version 1.8.0, it no longer works on python 2.6.

Here's the failure from `pip install yamllint` on python 2.6:

```
Collecting pathspec (from yamllint)
  Downloading pathspec-0.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/ly/g7l5bx455cq2c_r6z1ky8j1m0000gn/T/pip-build-y3oUIf/pathspec/setup.py", line 6, in <module>
        from pathspec import __author__, __email__, __license__, __project__, __version__
      File "pathspec/__init__.py", line 33, in <module>
        from .pathspec import PathSpec
      File "pathspec/pathspec.py", line 9, in <module>
        from . import util
      File "pathspec/util.py", line 167
        return {normalize_file(path, separators=separators): path for path in files}
                                                                    ^
    SyntaxError: invalid syntax
```

**Comment by adrienverge** [comment]
Hi,

Sorry to hear that. I was going to ask "is using 2.7 an option for you?" but I've just seen the problem in Ansible and I understand you cannot drop 2.6 support.

Unfortunately pathspec doesn't officially support Python 2.6: https://pypi.python.org/pypi/pathspec
I've opened https://github.com/cpburnz/python-path-specification/issues/16 to try to fix that.

**Comment by mattclay** [comment]
Fortunately this is only causing issues for us in CI. We don't have any Ansible modules or core functionality using yamllint. Limiting the version of yamllint that we use with python 2.6 (https://github.com/ansible/ansible/pull/26186) should provide an adequate work-around.

**Comment by adrienverge** [comment]
Thanks to you and @cpburnz, yamllint supports Python 2.6 again! (version 1.8.1)
