### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by adamchainz** [adrienverge/yamllint#57]
Upgrading from 1.7.0 to 1.8.0 and I have no idea what changed, which means I just have to yamllint all my files again and hope 😢  Can you add changelog/history file and keep track of what changes between releases? Thanks!

**Comment by zapashcanon** [comment]
There's [http://keepachangelog.com/](keepachangelog) which provides great guidelines.

**Comment by adrienverge** [comment]
done :)

**Comment by adamchainz** [comment]
Merci beaucoup!
