### ISSUE TITLE
Warning instead of error for variable indentation between siblings

### ISSUE THREAD

**Issue by 1605200517** [adrienverge/yamllint#58]
According to [specs](http://yaml.org/spec/1.2/2009-07-21/spec.html#id2576668), " the content of each sibling node may be further indented independently".

In such cases, this yamllint currently outputs an error. Maybe it should be a warning?

**Comment by adrienverge** [comment]
Hi,

The same applies to other rules: trailing spaces are allowed specs, spaces before colons are allowed specs, line can have any length, etc.

But yamllint is not about checking specs compliance ;-)
(Except if you disable all rules, in this case only syntax errors will be checked.)
