### ISSUE TITLE
No module named 'yaml' on MacOS

### ISSUE THREAD

**Issue by hhemied** [adrienverge/yamllint#583]
I'm getting the following errors when I run any related `yamllint` command.
```bash
➜ yamllint --help
Traceback (most recent call last):
  File "/usr/local/bin/yamllint", line 5, in <module>
    from yamllint.cli import run
  File "/usr/local/lib/python3.9/site-packages/yamllint/cli.py", line 27, in <module>
    from yamllint import linter
  File "/usr/local/lib/python3.9/site-packages/yamllint/linter.py", line 19, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

I used brew to install `yamllint` and ensured that `pyyaml` and `libyaml` are also installed.

**Comment by andrewimeson** [comment]
1. Is it a fresh installation from Homebrew and it broke immediately, or did it work for a while and upgrades may have broken it?
2. How did you install pyyaml and libyaml? Is it possible you installed them into a different Python environment?

Troubleshooting commands:

```
brew doctor
which python3
python3 -m pip freeze | grep -i -e yamllint -e pyyaml
```

To force a reinstall `brew uninstall yamllint && brew install yamllint`

**Comment by hhemied** [comment]
Thank @andrewimeson for the hint.
`brew doctor` showed unlinked formula
Now fixed and working again.
