### ISSUE TITLE
Python 3.7 is EoL

### ISSUE THREAD

**Issue by cpburnz** [adrienverge/yamllint#592]
I am looking into dropping support for Python 3.7 (which become EoL on 2023-07-26) for [pathspec](https://github.com/cpburnz/python-pathspec). *yamllint* is the one major dependent of *pathspec* that I'm aware of that still supports Python 3.7. [*ansible-lint*](https://github.com/ansible/ansible-lint) which is a dependent of *yamllint* has already moved to Python 3.9+. Do you intend to continue or drop support for Python 3.7?

**Comment by adrienverge** [comment]
Hello @cpburnz, this sounds like a good idea! Would you like to contribute by making a commit similar to e8391de (that dropped support for Python 3.6)? It would need a slight adaptation because of the switch to `pyproject.toml`.
