### ISSUE TITLE
Enable ruff format?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [adrienverge/yamllint#636]
[The Ruff Formatter](https://docs.astral.sh/ruff/formatter/)

**Comment by DimitriPapadopoulos** [comment]
To see how it formats Python source code, run:
```
ruff format .
```

**Comment by adrienverge** [comment]
I'm -1 to change the current source code and alter Git history for 65 files and ~10k lines of code. Also I don't have a problem with currently-used single quotes or mixed indentation when it helps readability.

**Comment by DimitriPapadopoulos** [comment]
Single quotes won't change:
- ruff has always been supporting single quotes,
-  black started supporting them recently.

I haven't investigated indentation.

**Comment by DimitriPapadopoulos** [comment]
While [`git blame --ignore-revs-file`](https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revs-fileltfilegt) is not perfect, it helps ignore changes related to formatting.

**Comment by DimitriPapadopoulos** [comment]
Let me run `ruff format` and try to minimize changes, so we can see the extent of changes.

**Comment by DimitriPapadopoulos** [comment]
[`indent-style`](https://docs.astral.sh/ruff/settings/#format-indent-style) is either `tab` or `space`.

**Comment by adrienverge** [comment]
Good that ruff supports mixed quotes :+1:
I see all the changes in https://github.com/adrienverge/yamllint/pull/638, and I still don't think it helps readability, especially about the mixed indentations I mentioned. And changing all these 63 files is not appealing...
