### ISSUE TITLE
Weird lint error on github action yaml

### ISSUE THREAD

**Issue by hholst80** [adrienverge/yamllint#656]
I have never seen a problem with the "on" key.  Truthy values are just that, values, not key properties.

![image](https://github.com/adrienverge/yamllint/assets/6200749/a035e23d-f09c-46d9-95b7-06b8828c0f2d)

```
[I] root@trump ~
# cat test.yaml
true: kalle
[I] root@trump ~
# yq -o xml < test.yaml
<true>kalle</true>
[I] root@trump ~
#
```

**Comment by adrienverge** [comment]
Please search for existing issues before opening new ones: #540, #430, #344, #232, #247, #158 and others. Thank you!
