### ISSUE TITLE
Rules details not functioning correctly on docs page

### ISSUE THREAD

**Issue by debarnard** [adrienverge/yamllint#66]
clicking any bold rule heading on this page  http://yamllint.readthedocs.io/en/latest/rules.html#id1
just sends you back to the rules list. The details for each rule are no longer visible.  I tried with chrome and IExplorer.

**Comment by adrienverge** [comment]
Builds are back to normal (see commit 59bdbf1) and rules are documented again on https://yamllint.readthedocs.io/en/latest/rules.html.

Thanks for reporting this!
