### ISSUE TITLE
Snap release

### ISSUE THREAD

**Issue by lengau** [adrienverge/yamllint#662]
yamllint would be a great tool to release with snap. I'd be happy to build the snap file (in fact [I already have](https://github.com/lengau/yamllint-snap) 🙂 ), register the name, etc.

If you'd prefer not to have the snap be official, let me know and I can publish it myself, ensuring the description indicates that it's unofficial.

Thanks in advance!

**Comment by adrienverge** [comment]
Hello Alex, thanks for the proposal and for creating a snap file :+1:

I encourage you to create the snap package, maintain it and stay close to upstream releases :)

**Comment by lengau** [comment]
Thanks! Will do!
