### ISSUE TITLE
Feature request: personal configuration (~/.yamllint)

### ISSUE THREAD

**Issue by dabrahams** [adrienverge/yamllint#669]
I'd like to change what's used by default by having a `~/.yamllint` configuration file.  That would be a nice feature.

**Comment by adrienverge** [comment]
Hello Dave,

You can use the environment variable `$YAMLLINT_CONFIG_FILE` for this purpose. Apart from that, adding new default paths for configuration is not planned. There is a general effort in the Linux distributions ecosystem to put configuration files into `~/.config` (see ), hence the choice made in yamllint.

**Comment by dabrahams** [comment]
Oh, I missed this in the docs!

> a file named `$XDG_CONFIG_HOME/yamllint/config` or `~/.config/yamllint/config`, if present

Sorry for the noise!
