### ISSUE TITLE
[Proposal] Key ordering rule

### ISSUE THREAD

**Issue by JFKnaufAncud** [adrienverge/yamllint#67]
In order to enforce uniform key ordering in a mapping I want to have a rule for checking lexicographical sorting.

**Comment by adrienverge** [comment]
Nice idea! Help welcomed.

**Comment by JFKnaufAncud** [comment]
Created a simple implementation based on key-duplicates. I tried to follow your example regarding docs, tests etc. as much as possible.

Looking forward to your review.
