### ISSUE TITLE
Old version in ubuntu repos

### ISSUE THREAD

**Issue by ReFruity** [adrienverge/yamllint#73]
`apt-cache policy yamllint`
```
yamllint:
  Installed: (none)
  Candidate: 1.2.1-1
  Version table:
     1.2.1-1 500
        500 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
```
It seems to be why `ignore` option was not working for me. Please update to 1.8.1 (or provide ppa?)

**Comment by gchianes** [comment]
I ran in to this too.  There is a workaround - download the source for 1.8.1 (or whatever version you want), untar it, and in the version directory, run:
$ sudo python setup.py sdist
$ sudo pip install dist/yamllint-*.tar.gz

I had two versions at this point, so I de-installed the Ubuntu version 1.2.1, which I should have done first.  You might have to close and reopen your terminal session or path the new version in /usr/local/bin

**Comment by ReFruity** [comment]
This should work but is inconvenient for every developer on our project to do.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by adrienverge** [comment]
@sandstrom I agree this issue is not relevant, since the Ubuntu package is not maintained here.
