### ISSUE TITLE
Release to handle the right pre-commit file

### ISSUE THREAD

**Issue by blackillzone** [adrienverge/yamllint#75]
Currently, using pre-commit, it only works using the master branch, because the last released version don't contain the right `.pre-commit-hooks.yaml` file.

When doing an auto-update with pre-commit:

```
Updating https://github.com/adrienverge/yamllint.git...An error has occurred: InvalidManifestError: 
=====> /home/fdhaussy/.cache/pre-commit/repoPsMzo4/.pre-commit-hooks.yaml does not exist
```

And it only works by setting master in our pre-commit files. Do you know when the next release, that will include the new pre-commit, will be out ?

Thanks !

**Comment by adrienverge** [comment]
Sure! I just released version 1.8.2.
