### ISSUE TITLE
Add rule for detecting empty (null) values

### ISSUE THREAD

**Issue by gdubicki** [adrienverge/yamllint#82]
Recently we run into an issue with a file that was supposed to have this:

```
foo::bar:
  something:
    aaa: bbb
```

...but instead it had this:

```
foo::bar:
something:
  aaa: bbb
```

I was a bit surprised to find out on this occasion that the latter is a correct syntax too and it means that "foo::bar" is set to empty (null) value.

But this doesn't make sense for us and I guess that for many other users. Therefore it would be nice to have a rule that would treat setting keys to empty (null) values as errors.

**Comment by adrienverge** [comment]
Agreed, this could be a useful rule.

Any contribution towards such an `empty-values` rule will be welcome (provided it comes with tests and documentation)!

**Comment by gdubicki** [comment]
Ok, I'll try to add it. :)

**Comment by adrienverge** [comment]
Implemented via `empty-values`.
