### ISSUE TITLE
can i bypass tab checking using yaml rules ?

### ISSUE THREAD

**Issue by r0ckyte** [adrienverge/yamllint#84]
Few of my Yaml files contain tabs at end of line. can i disable this using configuration. i dont want my yaml to fail with this error. 

Thank you

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by adrienverge** [comment]
I'll close since this "issue" is hard to understand, but looks like a "RTFM" one.
