### ISSUE TITLE
anchor references seen as duplicate key

### ISSUE THREAD

**Issue by neekz0r** [adrienverge/yamllint#88]
I'm not sure if this is a feature or a bug! :-)

When running yamllint on a yaml file with multiple anchors referenced, you get a duplicate key error. 

EG:

Given the following file:
```yaml
---
anchor_one: &anchor_one
  sequence_one:
    - sequence_one
    - sequence_two

anchor_two: &anchor_two
  sequence_two:
    - sequence_three
    - sequence_four

main:
  <<: *anchor_one
  <<: *anchor_two
  unicorn_settings:
    - non-sequence-sequence
```

Upon running yamllint you get the following error:
```bash
test.yml
  14:3      error    duplication of key "<<" in mapping  (key-duplicates)
```

Python thinks it's "valid" and has the desired data structure:

```python
>>> import yaml, pprint
>>> pp = pprint.PrettyPrinter(indent=2)
>>> file = open("test.yml", "r")
>>> yaml_dump = yaml.load(file)
>>> pp.pprint(yaml_dump)
{ 'anchor_one': { 'sequence_one': ['sequence_one', 'sequence_two']},
  'anchor_two': { 'sequence_two': ['sequence_three', 'sequence_four']},
  'main': { 'sequence_one': ['sequence_one', 'sequence_two'],
            'sequence_two': ['sequence_three', 'sequence_four'],
            'unicorn_settings': ['non-sequence-sequence']}}
```

[As near as I can tell, it seems to be supported by the YAML spec:](http://www.yaml.org/spec/1.2/spec.html#id2765878):

*When composing a representation graph from serialized events, an alias node refers to the most recent node in the serialization having the specified anchor. Therefore, anchors need not be unique within a serialization.*

**Comment by adrienverge** [comment]
Hi @neekz0r, it certainly looks like a bug!

I didn't know about this `<<` feature. Where is it described? I couldn't find it in the [YAML specification](http://www.yaml.org/spec/1.2/spec.html)!

I played with it a bit, and it seems there are other problems:

```yaml
duplicate keys:
  <<: {same key: value 1}
  <<: {same key: value 2}  # detected a duplicate for `<<`, not for `same key`
```

**Comment by neekz0r** [comment]
I had to look it up too! 

It was theoretically in the spec in 1.1, which the YAML 1.2 spec (which we both referenced) says it's supposed to be compatible with. Presumably, they expect people to go back and also look at 1.1 spec (and even perhaps 1.0 spec?) 

The feature is called [Merge Key Language-Independent](http://yaml.org/type/merge.html)

**Comment by perlpunk** [comment]
That YAML can actually be written like this to avoid duplicate keys:
```
main:
  <<: [ *anchor_one, *anchor_two ]
  unicorn_settings:
    - non-sequence-sequence
```

I believe that's the correct way, see https://yaml.org/type/merge.html
