### ISSUE TITLE
Disable document start checking

### ISSUE THREAD

**Issue by waghanza** [adrienverge/yamllint#92]
Hi,

I have some hand-written `yaml ` files. I have not put the `---` on each files.

Is there a way to disable document start rule ?

~~~
warning  missing document start "---"  (document-start)
~~~

Regards,

**Comment by adrienverge** [comment]
Hi, yes there is way, you'll find it in the README and the documentation.

**Comment by william-huma** [comment]
@adrienverge Could you let me know how to do it please?
