### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by Khalian** [adrienverge/yamllint#96]
If -c is not provided, yamllint will look for a configuration file in the following locations (by order of preference):

    .yamllint in the current working directory
    $XDG_CONFIG_HOME/yamllint/config
    ~/.config/yamllint/config

What is the name of this file?

**Comment by adrienverge** [comment]
I don't understand your question.

The documentation says:

> If `-c` is not provided, yamllint will look for a configuration file in the following locations (by order of preference):
> 
> - `.yamllint` in the current working directory
> - `$XDG_CONFIG_HOME/yamllint/config`
> - `~/.config/yamllint/config`
> Finally if no config file is found, the default configuration is applied.

What confuses you? `$XDG_CONFIG_HOME`? `~/.config/`?

**Comment by Khalian** [comment]
.config is a directory. What is the PRECISE file name it's looking for? I put in a yaml file with identical contents as the example given, and the linter completely ignored it.

**Comment by alexharv074** [comment]
I agree with @Khalian that this could be clearer. Because "config" sounds like it would be a directory, and you'd expect a file `~/.config/yamllint/config/.yamllint` to exist. Also surprising is that the config file, which is a YAML file, is not named `.yml`.

**Comment by DSpeichert** [comment]
> Also surprising is that the config file, which is a YAML file, is not named .yml.
THIS.
Hard to get proper formatting help from IDE without `.yml`.

**Comment by ChristianWeissCG** [comment]
Yamllint follows a common practice to name its config file based on the tools name prefixed with a dot  and optionally suffixed with a feature name as other tools do:
.gitignore
.dockerignore

As this ticket is about "improving the documentation" for (i guess) windows users, as windows users often think that `.someting`is a file extension, not a full file name, you can improve the situation by searching for a `.yamllint.yaml` and/or `.yamllint.yml`, this would help windows users to recognize this as a file and also improves the extension-based syntax highlighting in some editors/IDEs.

But then it is not only a improvement of documentation - it is a new feature (define precedence in docs).

**Comment by adrienverge** [comment]
@ChristianWeissCG thanks for your input.

I'm not for adding complexity by supporting multiple types of filenames at the same location.

Maybe the documentation can be improved by rewording the sentence:

> - `.yamllint` in the current working directory

?

**Comment by alexharv074** [comment]
I'm not a Windows user and I found this confusing, and inconsistent with other Linux tools. I didn't find `.yamllint` in itself so confusing. But then the additional files searched for are named differently and that led me to assume they must be directories. I guess if the docs are just clarified that those are actual file names it would be perfect.
